### ISSUE TITLE
Colour bug when loading comments

### ISSUE THREAD

**Issue by azzopalj** [christianselig/apollo-bugs#1005]
**Describe the bug**
When the app is in regular dark mode, when loading comments on a post, the loading icons cell is dark black

**To Reproduce**
1. Be in dark mode
2. Click on the post
3. Look at loading icon in comment section

**iOS version**: 14
**Apollo version**: 1.10
**iOS device**: iPhone 11
**Jailbroken**: no
**Reproducible:** yes

**Expected behavior**
The colour of the cell should match the background and not be pure black

**Screenshots**
![F291B297-9176-4158-91F6-266AAFF236D1](https://user-images.githubusercontent.com/32116466/93401756-f2a20d00-f850-11ea-86c3-15a3947a2eee.png)

.

**Comment by Jonah-B-Kehillah** [comment]
I am also getting this error on my `iPhone 7 Plus`.

**Comment by iiTzRichie** [comment]
Same thing for the panels on your Subreddit List, it has a different/distorted color.

https://i.imgur.com/q1D9fS9.jpg

**Comment by SiegfriedEhret** [comment]
Hey ! I also see this when there are no comments (iPhone 8, iOS 14, Apollo 1.10, not jailbroken, reproducible: yes): 

![image0](https://user-images.githubusercontent.com/537567/93448267-b1067600-f8d3-11ea-85cb-7a5ebf655136.png)

**Comment by kaktus1389** [comment]
Noticed the same things as others pointed out, present in the beta version on iOS 14 as well as on non-beta version of Apollo on iPadOS 14.

**Comment by indianimal** [comment]
Same thing happening to me. 
![0A9D8F8A-CB07-4097-A195-B9F3FB189E68](https://user-images.githubusercontent.com/71484327/93561013-40457500-f938-11ea-81eb-ff6ae05f89b7.png)
