### ISSUE TITLE
Widgets Showing wrong photo for posts.

### ISSUE THREAD

**Issue by pevd950** [christianselig/apollo-bugs#1007]
The only post with the correct image is the second one. The rest are switched around.

![IMG_0191](https://user-images.githubusercontent.com/12861801/93409292-36e6da80-f85c-11ea-910f-24c9307934a6.jpeg)

**Comment by TheBeachMaster** [comment]
Can confirm ![image](https://user-images.githubusercontent.com/9129843/93465397-65fc5b00-f8f3-11ea-9ffa-07179a9b1711.png)

**Comment by evanjs** [comment]
~Mmmm off by one errors.~
~Looks like everything is just bumped down by one, resulting in a blank thumbnail for the first post.~
So much for consistency. I guess the this is closer to undefined behavior.  

Also seeing this issue, anyhow.
