### ISSUE TITLE
Audio (and video) continues to after it is off the screen

### ISSUE THREAD

**Issue by CHCMATT** [christianselig/apollo-bugs#1044]
**Describe the bug**
Apollo sometimes continues to play audio even after video has been scrolled past, but it should stop audio and should not continue to play. Often this happens to me when I play a video with audio, click another video or two, and the audio from the first video and the current video are now playing. In the screen recording of this, the audio continues even when I am scrolling, which is not what I intended to show off but may be a separate (but could be related) bug.

**To Reproduce**
1. Play video
2. Continue scrolling (audio normally is muted at this point)
3. Play another video with audio unmuted
4. Now both video’s audio are playing at the same time when you only want the current video’s audio to play.

**iOS version**: 14.0
**Apollo version**: 1.10.3 (but started noticing after 1.10 update)
**iOS device**: iPhone 11
**Jailbroken**: No
**Reproducible:** Seems to happen commonly but I would say I don’t think it’s EVERY time. I think “most times” is a fair assessment.

**Expected behavior**
Audio and video should stop playing, and should no longer be accessible while another video is playing.

**Video**
https://streamable.com/84xb1z

**Comment by remicarreiro** [comment]
I've noticed the exact same issue.
