### ISSUE TITLE
incorrect markdown for code blocks - should be triple backticks (```) (not single)

### ISSUE THREAD

**Issue by chinarut** [christianselig/apollo-bugs#1057]
**Describe the bug**
When I select text as a code block, Apollo only uses single backticks when it should use triple backticks:

https://www.reddit.com/wiki/markdown#wiki_code_blocks_and_inline_code

**To Reproduce**
1. Submit Post
2. select Text Post
3. compose text
4. select a block of text
5. click ...
6. select “</> code”
7. witness it only puts single backticks

**iOS version**: 14.0.1
**Apollo version**: 1.10.3
**iOS device**: iPadPro (2018)
**Jailbroken**: No
**Reproducible:** Yes

**Expected behavior**
it should triple backticks (```) on both ends of the code block

**Additional context**
here is the markdown help text where I discovered the correct way to markdown a code block:
https://www.reddit.com/wiki/markdown#wiki_code_blocks_and_inline_code

here is a post that demonstrates triple backticks is correct:
https://reddit.com/r/ish/comments/j0nweb/what_is_correct_way_to_create_ishipa/ (open in desktop Safari, it is not rendered correctly in Apollo)

**Comment by BlazingFrag** [comment]
This is not always entirely correct. The switch to New Reddit changed how code blocks work … so now there are two accepted ways of denoting them. Old Reddit, which is still officially supported (and preferred in many subs) uses a quadruple space at the beginning of each line to denote code. Triple-backtick bounded code blocks are only supported on New Reddit.

Inline code, meanwhile, uses single backticks in both cases. So the issue isn’t that the button is broken _per se_; it’s just built for inline-code only (like \`this\`).

**Comment by chinarut** [comment]
thanks for all the hard work of the Apollo team.  Closing out this request and thanks for clarifying.
