### ISSUE TITLE
Keyboard auto collapses when trying to search Reddit.

### ISSUE THREAD

**Issue by ThePugPrince** [christianselig/apollo-bugs#1063]
**Describe the bug**
Keyboard auto collapses when I’m typing in the search bar for subreddits. Only lets me type a single letter then I have to retap the search bar to finish what I was typing.

**To Reproduce**

1. Go to the search option at the bottom 
2. Press on the search bar at the top of the screen
3. When you type any letter of the subreddit you want to search for it auto collapses the keyboard and shows the first results instead of letting you finish typing
4. I have to go back to the top of the screen and press on the search bar again to finish my initial search.

**iOS version**: IOS 14
**Apollo version*: 1.10.3
**iOS device**: iPhone 11 Pro Max
**Jailbroken**: My device is not jail broken
**Reproducible:** This occurs every time I’d like to search the whole of Reddit for a subreddit

**Expected behavior**
I expect when I start typing in the search bar that the app will let me finish typing the initial subreddit name and then I manually collapse the keyboard or I press on a subreddit for the keyboard to disappear. The auto collapse after a single letter has gotten bothersome. But I love this app and will keep supporting you.

**Screenshots**
Cannot provide screen shots

**Video**

https://gfycat.com/equatorialorderlyanophelesmosquito

**Additional context**
Just a simple bug or it might be an option added that I do not know how to deactivate.

**Comment by DrZangariSlifkin** [comment]
I have this same issue
iOS version: IOS 14.2 beta 2
*Apollo version: 1.10.3
iOS device: iPhone 11 Pro Max
Jailbroken: My device is not jail broken

**Comment by ezucs** [comment]
I have the same issue.
iOS 14.1
Apollo 1.10.4
iPhone 11 Pro Max 
Not jailbroken

**Comment by lKnowKungFu** [comment]
I’m experiencing this too. 

iOS 14.2.1
Apollo 1.10.99
iPhone 12 Pro Max
Not jailbroken

**Comment by skeith** [comment]
Mentioning issue #1033 which is the earlier report about this particular bug

**Comment by skeith** [comment]
Issue seems to be gone from Apollo 1.10.5 on iPhone, iOS 14.2
