### ISSUE TITLE
Collapse AutoModerator not working

### ISSUE THREAD

**Issue by petebocken** [christianselig/apollo-bugs#1107]
**Describe the bug**
I’ve had Collapse AutoModerator enabled ever since it was released and suddenly it is no longer working. Possibly since 1.10.4?

**To Reproduce**
1. Go to Settings
2. Click on General
3. Scroll down to Collapse AutoModerator and Enable
4. View any post that has an AutoModerator comment

**iOS version**: 14.0.1
**Apollo version**: 1.10.4
**iOS device**: iPhone X
**Jailbroken**: No
**Reproducible:** Yes

**Expected behavior**
AutoModerator comments should be collapsed

**Screenshots**
https://i.imgur.com/pEnewr9.jpg
https://i.imgur.com/tkehmKm.jpg

**Comment by buttonpushertv** [comment]
I have the same the issue. Not working anywhere for me.
