### ISSUE TITLE
iOS 13 DB1 (17A5492t) Apollo 'forgets' all reddit accounts that are set up

### ISSUE THREAD

**Issue by itslazyvar** [christianselig/apollo-bugs#120]

**Comment by FuturePilot** [comment]
This happens to me quit frequently. I’ve noticed it seems to always happen after changing networks ie Wifi to mobile or vice versa and usually the app wasn’t resumed from the background but was a full reload. Did it happen to you after a network switch from the last time you had the app open?

**Comment by TorchedPoseidon** [comment]
@FuturePilot Hmm, hard to say, the refreshing of the Reddit token as mentioned in the logs happened while I was connected to wifi which is what I am almost always, the nexts day when I discovered all the accounts and disappeared was on cellular. It might've been a full reload, I know the app has been long enough in the background for it to be suspended, on the other hand the logs show a move to background and move to foreground event, suggesting that a reinitialisation would've been logged as well.
