### ISSUE TITLE
Share as image doesn’t contain post image (sometimes)

### ISSUE THREAD

**Issue by barbados-clemens** [christianselig/apollo-bugs#1243]
**Describe the bug**
When sharing a post as image, including the image doesn't work, just shows link to image vs showing image only after scrolling far enough down within the post. 

**To Reproduce**
1. Go to https://reddit.com/r/BlackPeopleTwitter/comments/m9d0rc/it_turns_out_that_benadryl_is_a_sleep_aid_in/
2. Click on share share as image from share sheet. 
3. Include post details
4. Cancel
5. Scroll down a couple top comments (worked after two for me) 
6. Share as image again with post details. Image preview isn't shown. 

**iOS version**: 14.4 (18D52)
**Apollo version**:  1.10.6
**iOS device**: iPhone X
**Jailbroken**: false
**Reproducible:** can reproduce

**Expected behavior**
Expect image preview to be within post details. 

**Screenshots**
![post without image preview](https://user-images.githubusercontent.com/23272162/111887134-044fa300-89a1-11eb-89d7-489036881416.png)
![post with image preview](https://user-images.githubusercontent.com/23272162/111887151-1a5d6380-89a1-11eb-991e-6f1ff73fccea.png)
**Video**

![example of bug](https://user-images.githubusercontent.com/23272162/111919805-cfebed80-8a59-11eb-8ab5-c59f4aa12d0a.MP4)

 

**Additional context**
I don't know jack about iOS development. I'm a simple web developer. But it seems as though the image preview gets unloaded when scrolls so far out of view; therefore, when generating the image preview it can only show the link vs image preview. Just a wild guess.

**Comment by CDeLeon94** [comment]
Also seeing a similar issue. 

Apollo 1.11.6 Ultra_Pro
iOS 15.1
iPhone 11 Pro

1. Find image post
2. click into the post
3. click 3dot menu
4. click share as image
5. see the rendered image to be shared, is missing the post image


Works correctly here:

1. Find a image post
2. long press on the title of the post
3. click share as image
4. rendered preview has the image from the post
