### ISSUE TITLE
About/Apollo Pro section wrong content  size

### ISSUE THREAD

**Issue by mattiacantalu** [christianselig/apollo-bugs#1258]
**Describe the bug**
Entering into About/Apollo Pro section the view has wrong content size and the bottom/upper content is hidden.

**To Reproduce**
Settings (tab) - About - Apollo Pro

**iOS version**: tested in iOS 14.4 and iOS 14.5 beta

**Apollo version**: 1.10.99 (86.2)
**iOS device**: iPhone X, iPhone XR
**Jailbroken**: no jb 
**Reproducible:** systematic 

**Expected behavior**
The content should be correctly shown without go over margins.

**Screenshots**
![image](https://user-images.githubusercontent.com/15363117/113824551-3bcf9500-9780-11eb-9755-f565f8a8292c.png)

![image](https://user-images.githubusercontent.com/15363117/113824562-3eca8580-9780-11eb-9118-a74a62751ae7.png)

**Video**
https://gfycat.com/brisksoggyasiandamselfly

**Comment by christianselig** [comment]
Fixed thanks!
