### ISSUE TITLE
Playing video opens youtube app even though ‘open in youtube’ is disabled

### ISSUE THREAD

**Issue by mcx808** [christianselig/apollo-bugs#1315]
**Describe the bug**

**To Reproduce**
iPadOS 14.5.1 and Apollo 1.10.8
Youtube app installed
‘Open videos in youtube app’ is disabled in apollo settings > general
Go to this post and tap play. Youtube app opens.
https://reddit.com/r/apple/comments/ngms0b/assistivetouch_for_the_apple_watch/

**iOS version**: 14.5.1
**Apollo version**: 1.10.8
**iOS device**: iPad Pro 11
**Jailbroken**: No
**Reproducible:** Yes

**Expected behavior**
Video should play in apollo

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by cjtylr** [comment]
Hey there, just wanted to say I’m having the same (or a similar) issue. In the last day or two, YouTube links have stopped playing in the media viewer and have instead opened using in-app Safari.

**Comment by mcx808** [comment]
Yes, I’ve also now had the same issue on iPhone iOS and with every youtube video as far as I can tell.

**Comment by cjtylr** [comment]
This issue was fixed for me in 1.10.9. Thanks!

**Comment by mcx808** [comment]
Confirmed for me too, fixed in 1.10.9.

**Comment by cjtylr** [comment]
This issue returned for me yesterday. Looks like I’m still on 1.10.9, so I’m curious what the root cause might be. @mcx808 - are YouTube videos still opening in the media viewer for you or has the issue returned for you as well?

**Comment by mcx808** [comment]
Yes, I have the issue again in 1.10.9.

**Comment by christopherjtaylor** [comment]
@christianselig Hey there, just want to make sure you’re aware of this issue. Can’t play any YouTube-sourced video in the media viewer at the moment. Thank you in advance!

**Comment by cjtylr** [comment]
This is an interesting bug. For the first half of July, videos were correctly opening in the media viewer. Over the last week or two, they’re back to opening in the in-app browser. I’m on 1.10.11; happy to provide logs or something if helpful.

**Comment by cjtylr** [comment]
This is fixed for me in 1.10.12.

**Comment by christianselig** [comment]
Should be fixed now!

**Comment by mcx808** [comment]
Confirmed fixed in 1.10.12. Thanks!
