### ISSUE TITLE
GIFs are black

### ISSUE THREAD

**Issue by lukearnould** [christianselig/apollo-bugs#135]
**Describe the bug**
When GIFs are opened and played they will be black despite the progress bar showing that they are playing. 

**To Reproduce**
1. Go to this link: https://reddit.com/r/iOSBeta/comments/c0v4cj/feature_with_the_new_shortcuts_automations_you/
2. The GIF appears to be loaded and playing, but when you tap on it to make it fullscreen, it goes black. 
3. This happens with almost any GIF I’ve viewed, the link is just one example. 

**iOS version**: 12.3.1
**Apollo version**: 1.4.21
**iOS device**: iPhone 7
**Jailbroken**: No
**Reproducible:** Every time with the given link
**Expected behavior**
The GIF should play normally.

**Comment by blanketyblank901** [comment]
This is now happening to me as well. Very frustrating.

**Comment by ettpok** [comment]
I have a similar case as well, with the exception that the GIFs turn black only if I turn the phone from portrait to landscape

**Comment by SteveLockeUK** [comment]
I’m also seeing GIFs fail to render once the device has been rotated
