### ISSUE TITLE
Apollo not Loading

### ISSUE THREAD

**Issue by terminatort1800** [christianselig/apollo-bugs#1355]
**Describe the bug**

Once we open the App, it’s blank. Nothing is loading. None of the subreddits that I’m subscribed to are coming up. Just blank with a small white cartwheel at the blank homepage of the App

**To Reproduce**
1. Go to '...' Apollo
2. Click on '....' Apollo 
3. Scroll down to '....' no scrolling because there’s nothing to scroll

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General) 14.6
**Apollo version**: Version of Apollo this bug occurred on (can be found in Apollo's Settings tab > About)
**iOS device**: For example iPhone XS, iPad mini, etc. - IPhone XR
**Jailbroken**: Whether or not your device is jailbroken - No jails were broken 
**Reproducible:** Can you reproduce it every time? Or is it random? - Yes. Still the same blank page 

**Expected behavior**
 Normally Reditt just pops up 
**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by terminatort1800** [comment]
![3091359A-8336-402B-A286-AAFDDEBCED66](https://user-images.githubusercontent.com/80042642/123339731-73372c00-d58e-11eb-8f80-643ca786708e.png)
![36C0AB74-451E-4654-8C9B-D2DBD97CA54D](https://user-images.githubusercontent.com/80042642/123339735-76321c80-d58e-11eb-96e5-ea4abd42317e.png)
![43C223A3-CC86-4D8A-A3E1-7B3B2528D253](https://user-images.githubusercontent.com/80042642/123339738-77634980-d58e-11eb-88e6-18a413e46d45.png)

**Comment by Saravia83c** [comment]
- - [ ] - ![image](https://user-images.githubusercontent.com/79783333/123372951-676d4a80-d539-11eb-876b-e87020119fba.png)

**Comment by terminatort1800** [comment]
All good now.
