### ISSUE TITLE
Notification duplicates

### ISSUE THREAD

**Issue by PartyingChair** [christianselig/apollo-bugs#1400]
Hello, 

in iOS 15 I have Apollo notifications sent to the notification summary and this happens. I’m sure it’s related to iOS 15, but just so you know 
![065E5382-D538-4D2F-B2B0-D6BF5FFF497D](https://user-images.githubusercontent.com/74517189/127534806-d77b9db7-0f01-46c8-a4cb-e7ac69a33282.png)
![Uploading FBB01A45-DD0B-4208-8DCF-D5726D13738C.png…]()

**Comment by Naxterra** [comment]
Still happening in iOS 15.2

![Uploading BC0A11A6-B840-42BD-904A-C148282136D9.png…]()
