### ISSUE TITLE
Apollo crashed when opening GIF

### ISSUE THREAD

**Issue by noodlezoodle** [christianselig/apollo-bugs#141]
**Describe the bug**
When clicking the GIF, Apollo will crash.

**To Reproduce**
1. Go to 'Home/Post'
2. Click on 'GIF'

**iOS version**: 10.3.3
**Apollo version**: 1.4.22
**iOS device**: iPhone 6
**Jailbroken**: Yes
**Reproducible:** Yes

**Expected behavior**
GIF playing.

**Video**
https://streamable.com/zm0lm

**Comment by babakoban** [comment]
I'm having the same issue.

iOS version: 10.2.1
Apollo version: 1.4.23
iOS device: iPhone 5s
Jailbroken: No
Reproducible: Yes

**Comment by babakoban** [comment]
Still having this issue whenever I try to open any GIF

**Comment by zedekblue** [comment]
ios 10.3.2, also having this issue
Workaround is to open comments, gif will play at the top 'media area' and you can click to open it there without crashing.
Crash only occurs when clicking on the thumbnail of gifs.

**Comment by babakoban** [comment]
@zedekblue I'm able to view them from the comments, but when I open it it still crashes.
The workaround I ise is to hold down the thumbnail and open it in safari.
I've also had one instance of trying to open a gif and having my phone crash and restart.

**Comment by noodlezoodle** [comment]
1.4.25 has fix this issue. :)
