### ISSUE TITLE
Unable to use Apollo Ultra perks after version 1.11 update

### ISSUE THREAD

**Issue by Blobert1747** [christianselig/apollo-bugs#1429]
**Describe the bug**
I just updated the iOS app after updating to iOS 15 and whenever I try to do something that requires the ultra subscription,it prompts me to purchase "Apollo Pro", but in the settings it says i've already purchased Apollo Ultra. Clicking "Restore" doesn't do anything either.

**To Reproduce**
1. Go to any Apollo plus feature with Ultra
2. Click on the feature 
3. See error

**iOS version**: 15.0
**Apollo version**: 1.11
**iOS device**: iPhone Xr
**Jailbroken**: No

**Screenshots**
Proof of purchase:
![image](https://user-images.githubusercontent.com/91101357/134093891-5dcb93a3-f512-426a-9915-7f10567aee67.jpeg)

Trying to change app icon: 
![image](https://user-images.githubusercontent.com/91101357/134093920-3dd33666-ccb0-48c5-806b-8890c68ea011.jpeg)

**Video**

https://youtube.com/shorts/OVYHJW9RnU4?feature=share

**Additional context**
I've had Ultra for almost 4 months now and this is the first time it has happened. I still have everything enabled from the Ultra subscription, but I cannot change, enable/disable, or use any Pro/Ultra options unless I pay for Pro again, which I really do not want to do since I already paid. Clicking "Restore" does nothing.

**Comment by christianselig** [comment]
Appreciate the detailed report. Fix has been submitted to Apple pending approval.

**Comment by shahanesalil** [comment]
Same issue here. Does the 1.11.1 fix it ? I updated the app to 1.11.1 and the issue still isn’t fixed for me. 
Earlier, the unlock pro option at the top in settings would disappear once you restore purchase. 
The weird thing is some pro / ultra features work for me but the others don’t. 
Video : https://share.icloud.com/photos/0aRdzrvIurycylMAiFlrVr8bA

iPhone 12, iOS 15.

**Comment by cdcoker** [comment]
Just updated to 1.11.1 and still having issues with Pro/Ultra features. Lacking scrubbing in gifs and videos. My theme and icon remain updated to pro versions but selecting new ones triggers a pro pop up.

iPhone 12 iOS 15

**Comment by christianselig** [comment]
Thought I fixed it, now a real-actualy-for-real submission is going to Apple!

**Comment by AlexanderCecile** [comment]
I was also having this issue, update 1.11.2 seems to have fixed it. Thanks!

**Comment by cdcoker** [comment]
Fixed with the 1.11.2 update! Thank you!!

**Comment by shahanesalil** [comment]
Can confirm also. Pro / ultra issues fixed with 1.11.2. Thank you!

**Comment by christianselig** [comment]
Woohoo! Closed then. :D
