### ISSUE TITLE
Face ID Lock Screen comes up when selecting search bar

### ISSUE THREAD

**Issue by at3089** [christianselig/apollo-bugs#1433]
**Describe the bug**
When I try to click the search bar after unlocking the app with Face ID, the white screen with the lock appears and covers half the screen. The keyboard still appears and I can type. And through the blurred background I can see that the search appears to be working as I type. 

**To Reproduce**
1. Close the app in the switcher
2. Open the app
3. Unlock app with Face ID 
4. Click search bar on the top of the posts tab 

**iOS version**: iOS 15
**Apollo version**: 1.11
**iOS device**: iPhone 12 Pro Max
**Jailbroken**: No
**Reproducible:** Reproducible

**Expected behavior**
I expect to be able to search as normal, without the Lock Screen coming up and obscuring the window. 

**Screenshots**
![image](https://user-images.githubusercontent.com/18405797/134172156-ee25df01-28ee-4aa2-9d49-928072c426f9.png)

**Video**
https://user-images.githubusercontent.com/18405797/134172455-282307c8-fe72-4832-937c-eb8866e1c827.MOV

**Additional context**

**Comment by kdu3142** [comment]
It's also happening to me when I open a video, or try commenting.

**Comment by FreakX23** [comment]
Same here, opening a Video or trying to comment gets me the FaceID lockscreen.

iOS 15 on an iPhone 11.

**Comment by eytanschulman** [comment]
This is also happening when tapping on the "title" field to enter for a new post on a subreddit.

See in this video:
https://user-images.githubusercontent.com/2043243/134208686-d30a37cb-433d-44e7-969d-c3ec72b92d6c.MOV

Running Apollo 1.11.1, iPhone 12 Pro, iOS 15.0 (19A344)

**Comment by sailingjab1976** [comment]
Yes I have the same issue as well. I have to close the app and then restart it.

**Comment by chrismarquardt** [comment]
+1

**Comment by eytanschulman** [comment]
There seem to be two other issues with the same problem, potentially duplicates https://github.com/christianselig/apollo-bugs/issues/1443 and https://github.com/christianselig/apollo-bugs/issues/1440

**Comment by tgansertdoe** [comment]
I have this issue with fingerprint ID on iPad Pro w ios15. Looking forward to a fix on this! Thanks C.S.!

**Comment by bds67** [comment]
I'm having the same issue with iPad 10.2 fingerprint id running iOS 15 and Apollo 1.11. When clicking the speaker button to hear audio or clicking the video to fill the screen, the image goes blurry and requests fingerprint id. The only way to see the video is to press the home button to see the video in a smaller window and then press the button for full screen, fingerprint id, and continue watching.

**Comment by at3089** [comment]
Looks like this was fixed in 1.11.2 🎉
