### ISSUE TITLE
GIFs from certain sources don’t load/play

### ISSUE THREAD

**Issue by angadsri** [christianselig/apollo-bugs#144]
**Describe the bug**
GIFs directly uploaded to Reddit, and many Gfycat GIFs that are especially large often have trouble loading and/or playing. I often have to open the content link in Safari to see them, and it wasn’t initially troublesome, but I think it’s happening increasingly often. Tapping to expand the GIF and waiting for it to load doesn’t work, and the barbershop sign waiting-to-load indicator at the bottom of the screen just stays at zero progress. 

**To Reproduce**
Steps to reproduce the behavior: it’s quite variable, and apparently depends on sub + gif size + source. 

**iOS version**: 13 developer beta 2
**Apollo version**: 1.4.23
**iOS device**: iPhone Xs 
**Jailbroken**: No
**Reproducible**: Random

**Expected behavior**
The GIFs to load and play as normal.

**Comment by kcmannem** [comment]
I’ve seen this too pretty often. If you tap on the gif and start scrubbing, it starts to play again.

**Comment by angadsri** [comment]
@kcmannem I think we might actually have different issues, because from “playing again” I infer you manage to get the GIF playing at least initially. In my case, nothing even loads up, and my screen remains blank/dark, even when I tap into the GIF to make it expand (and normally allow me to scrub).

**Comment by TheBKBurger** [comment]
This issue still happens to me as well. 

iOS 13 beta (not 13.1) 

Apollo 1.5.
