### ISSUE TITLE
White top/bottom

### ISSUE THREAD

**Issue by joeGerner** [christianselig/apollo-bugs#1454]
**Describe the bug**
When I open the sidebar of any Subreddit the top and bottom get black although darkmode is activated. 

**To Reproduce**
1. Go to 'any Subreddit'
2. Click on 'their sidebar'
3. See error

**iOS version**: 15.0
**Apollo version**: 1.11.2
**iOS device**: iPhone 13 Pro Max
**Jailbroken**: no
**Reproducible:** yes

**Expected behavior**
Top and bottom borders with the same colors as set 

**Screenshots**
https://imgur.com/a/OOoKxOr

**Video**

**Additional context**

**Comment by myleskeeffe** [comment]
Can confirm also happens to me. A few issues for this exist - maybe best to use #1450 (it’s the oldest for the issue)? Might help to tidy up the issues and make it slightly easier to sort through :)
