### ISSUE TITLE
Many DNS queries for `apollogur.download` domain, even without the app running in the background

### ISSUE THREAD

**Issue by PSalant726** [christianselig/apollo-bugs#1480]
**Describe the bug**
I use the [NextDNS](https://nextdns.io/) resolver and my logs show between 3 and 5 DNS queries per minute to the `apollogur.download` domain, even when the app has been force-closed and is not running in the background. My logs are not able to determine which app is making these DNS queries, just that they’re coming from my iPhone, but from some web searching it seems like this is a custom imgur proxy used by Apollo?

**To Reproduce**
1. Install Apollo
2. Run Apollo
3. Force-quit Apollo
4. Observe DNS query logs

**iOS version**: 15.0.1
**Apollo version**: 1.11.2
**iOS device**: iPhone 12 Pro
**Jailbroken**: No
**Reproducible:** Consistent behavior

**Expected behavior**
DNS queries for `apollogur.download` should only be made when imgur resources are required.

**Comment by LukeWheeldon** [comment]
Issue replicated here.

I'll add that I also have about as many queries for apollogur.download as I have for apollopushserver.xyz. I have about 5k queries for each of those domains within the past 24 hours.
