### ISSUE TITLE
Family Sharing not working

### ISSUE THREAD

**Issue by sohansubhash** [christianselig/apollo-bugs#1577]
**Describe the bug**
Not able to restore my lifetime Ultra purchase on a family members iPhone.

**To Reproduce**
1. Go to AppStore Family Purchases and download Apollo from a family members purchased list
2. Click on Purchase Ultra in the settings tab in Apollo
3. Click on Restore Purchase
4. A pop up will say nothing was found

**iOS version**: 15.2
**Apollo version**: 1.12
**iOS device**: iPhone 13 mini
**Jailbroken**: No
**Reproducible:** Yes

**Expected behavior**
When I click on restore purchase on a family members device Ultra should be unlocked via family sharing.

**Comment by fuzzman88** [comment]
I can’t figure out how to vote on this but to give it more attention but… I’m seeing the same behavior.
