### ISSUE TITLE
Video is not playing

### ISSUE THREAD

**Issue by albihasani94** [christianselig/apollo-bugs#1591]
**Describe the bug**
Came across a video which could not play on Apollo v1.12. Controls show it is playing but I get a black screen. Tested in on Safari and it works.

**To Reproduce**
1. Go to https://reddit.com/r/panda/comments/s3tv0p/angry_panda/
2. Play
3. See black screen

**iOS version**: 15.2
**Apollo version**: 1.12
**iOS device**: iPhone 13 Pro
**Jailbroken**: No
**Reproducible:** Yes, after reopening. But only on the same video.

**Thanks for making Apollo**

**Comment by albihasani94** [comment]
This seems to be solved with v1.12.1

**Comment by mjonkus** [comment]
I still have this issue even with 1.12.1

iOS version: 15.2
Apollo version: 1.12.2
iOS device: iPhone SE (2020)
Jailbroken: No
Reproducible: Yes, none videos play. All are stuck in pause. I can scrub, but cannot start to play. Did not exist in prev version.

**Comment by mjonkus** [comment]
It started working today. So no issue on my side anymore.

**Comment by albihasani94** [comment]
Nice! In that case I will close it.
