### ISSUE TITLE
Widget shortcut opens Apollo with a Reddit.comreddit.com page loop

### ISSUE THREAD

**Issue by kpyezdani** [christianselig/apollo-bugs#1599]
**Describe the bug**
On opening a post from the widget. 

See attached gif 

iOS 15.1
iPhone XS Max

apollo 1.12.1

Not jailbroken

**Comment by anon238** [comment]
I have the same issue, do you want a separate ticket? @christianselig

**Comment by layandreas** [comment]
Same here, I also get redirected to external ads.

**Comment by christianselig** [comment]
Fix submitted! @layandreas could you elaborate? I'm not sure I understand what you mean

**Comment by layandreas** [comment]
> Fix submitted! @layandreas could you elaborate? I'm not sure I understand what you mean

I wrongly assumed I was redirected to an ad website as my ad blocker blocked the loaded page. However it was still Reddit.comreddit.

**Comment by abeardedsloth** [comment]
Mine is doing this as well if I am opining Apollo from the widget. If Apollo is already running in the background, it works with no problem

iPhone 12 Pro
15.1.1

**Comment by christianselig** [comment]
Update, should be fixed in newest version approved today! :D
