### ISSUE TITLE
Scrolling comments with links can collapse thread

### ISSUE THREAD

**Issue by norigantz** [christianselig/apollo-bugs#162]
**Describe the bug**
Scrolling through comments with links throughout in certain positions and settings can cause the comment to become highlighted as if being long-pressed and prevent scrolling. Holding this state will not cause the long-press menu to appear. Letting go of the comment will cause the thread to be collapsed. If the top of the comment is low enough, dragging above the top of the comment will un-highlight the comment. Otherwise, the collapse seems unavoidable once this state is entered. Sometimes, like when I try to take a screenshot of this state, the bottom and top bar of Apollo disappear even though I have the bars set to remain on screen at all times (second image).

**To Reproduce**
1. Visit a long comment with links throughout, such as [this one](https://www.reddit.com/r/GameDealsMeta/comments/c5blpw/steam_summer_sale_2019_hidden_gems_thread/es0uf2d/).
2. Scroll to a position where a link is near the bottom bar, but leave enough space so that some plain text is in between the link and the bar, something like the position in the screenshot below.
3. Initiate a scroll by touching between the link and the bottom bar and dragging toward the top of the device
4. Result: the comment becomes highlighted and prevents scrolling

**iOS version**: 12.4
**Apollo version**: 1.4.25
**iOS device**: iPhone X
**Jailbroken**: No
**Reproducible:** 50% / High

**Expected behavior**
Scrolling through comments with links does not highlight the comment and prevents scrolling.

**Screenshots**
<img src="https://user-images.githubusercontent.com/9125898/60679991-ae973800-9e57-11e9-8dc2-86df8fd99b14.PNG" width = 40%> <img src="https://user-images.githubusercontent.com/9125898/60680299-ba372e80-9e58-11e9-8351-c2d22bc375e4.PNG" width = 40%>

**Video**
https://streamable.com/zs6z8

**Additional context**
Tap to Collapse is enabled.
Hide bars when scrolling is disabled.

**Comment by sojournerTim** [comment]
This is a long standing issue I’ve encountered as well. It is perfectly described above and still happens even on the latest version. Any update on this issue since it’s coming up on a year old?

**Comment by jorwex** [comment]
Is this the bug referenced in the changelog for 1.10.8 released yesterday?

> - Fixed bug where when dragging your finger sometimes Apollo would incorrectly interpret it as a tap to collapse

**Comment by norigantz** [comment]
Seems like it's been addressed! I could not reproduce the issue using the example post in the latest version. Looks like I can close this now.
