### ISSUE TITLE
Open in Apollo doesn’t work for old.reddit

### ISSUE THREAD

**Issue by alexcroox** [christianselig/apollo-bugs#1665]
Open in Apollo works great for the top level reddit domain but doesn’t for the old. subdomain. 

Click link from external application to an old.reddit.com link and safari won’t trigger the opening of Apollo

**Comment by BugDave** [comment]
I would love for this to be resolved. Most of the Reddit links are shared to me by people who use old.reddit.com

**Comment by quinncomendant** [comment]
Same here. This should be a trivial fix. @christianselig, this is low-hanging fruit.

Opening a link to `old.reddit.com` always shows the website:

<img src="https://user-images.githubusercontent.com/6884276/208269657-7c9af7b4-0998-45ea-85fc-27fddbdfdde2.jpeg" width="30%" height="30%">

Opening a link to `www.reddit.com` always shows the Open in Apollo launch screen: 

<img src="https://user-images.githubusercontent.com/6884276/208269658-5a18c777-74f6-47d3-91a8-18d295631c5f.jpeg" width="30%" height="30%">

**Comment by BugDave** [comment]
It’s fixed as of v1.15 which was released today! 👏🏻👏🏻 can someone mark as fixed? Thanks

**Comment by christianselig** [comment]
That's me!
