### ISSUE TITLE
Search box missing after using left screen edge swipe on iPad

### ISSUE THREAD

**Issue by the-ress** [christianselig/apollo-bugs#17]
**Describe the bug**
Search text box is missing after returning to the search screen using left edge swipe on iPad.

**To Reproduce**
1. Go to Search tab
2. Tap the search text box
3. Type ‘iamthatis’
4. Tap Go to user “iamthatis”
5. Swipe from the left screen edge
6. See the search text box missing

**iOS version**: 12.3
**Apollo version**: 1.4.18
**iOS device**: iPad Pro 10.5”
**Jailbroken**: No
**Reproducible:** Yes

**Expected behavior**
The search box should be there.

**Screenshots**
![126D3FB6-0AC5-4989-B7D6-691939132D91](https://user-images.githubusercontent.com/1612377/57282212-e0d12700-70ac-11e9-8c0a-55bcfe197812.png)

**Video**
![](https://im4.ezgif.com/tmp/ezgif-4-de86f78d9cec.gif)

**Comment by Taxyovio** [comment]
Same on my iPad Pro 10.5. 100% reproducible.

**Comment by yoBoss283** [comment]
Same on iPad mini 2019.
