### ISSUE TITLE
Subreddit Watcher Notifications Lost/Deleted Periodically

### ISSUE THREAD

**Issue by btrautmann** [christianselig/apollo-bugs#1772]
**Describe the bug**
After an indeterminate amount of time, subreddit watcher notifications disappear/stop working. In other words, previously configured watcher notifications can no longer be found when navigating to Settings -> Notifications and they don't notify the user either. This was originally raised [here](https://www.reddit.com/r/apolloapp/comments/v8fzku/watcher_filter_getting_reset_when_app_is_in_the/) by another user.

**To Reproduce**
1. Set up a Subreddit Watcher notification (I use the "title contains" filter)
2. These notifications will work for an unknown period of time (days to weeks)
3. Eventually, notice that you stop receiving notifications
4. Navigate back to Notifications and they're all gone

**iOS version**: 15.5
**Apollo version**: 1.13.1
**iOS device**: iPhone 11
**Jailbroken**: Not jailbroken
**Reproducible:** Has happened both times I've set up notifications, but at random intervals

**Expected behavior**
Configured subreddit watcher notifications should persist and work/notify until deleted.

**Screenshots**
N/A

**Video**
N/A

**Additional context**
The first time I noticed this, my monthly PRO subscription had just renewed. I set the watcher notifications back up and they were again deleted days later.

**Comment by caffeinatedwater** [comment]
I have the same issue on an iPhone 12, I set a bunch of watchers/trending/reminders and some days later all of them get reset. It happened 6 times already since the new notification screen was added, including one today with iOS 16 and Apollo 1.14.2.
