### ISSUE TITLE
Text input box when replying doesn't get large enough to see all of the entered text

### ISSUE THREAD

**Issue by mvan231** [christianselig/apollo-bugs#1782]
**Describe the bug**
when replying to a post or someone's comment, the text input field doesn't grow large enough to see the text that has been entered. It only lasts long enough for around 3-4 lines of text

**To Reproduce**
1. Reply to a post or a comment
2. start typing and enter enough text to reach down 3-4 lines or more
3.  you will see that you can't see the text you are typing after some certain point 

Note: this can also be seen by trying to edit a large comment or post that is already existing. 

**iOS version**: 16.0 beta dev beta 5 (16.0 (20A5339d))
**Apollo version**: 1.13.1
**iOS device**: iPhone 12
**Jailbroken**: Not jailbroken
**Reproducible:** every time

**Expected behavior**
I should be able to see my entered text

**Screenshots**
If possible, add screenshots to help show the problem.
![9BE3D400-CD07-456C-A767-D678ECD27C8F](https://user-images.githubusercontent.com/50910610/184531609-6f379f46-2436-4288-b163-c73c11ac9612.png)
![21489697-5EF0-43A7-9B81-D0EBD6BE7544](https://user-images.githubusercontent.com/50910610/184531610-82655b74-0427-47a8-bd2f-c92aad7313fc.png)

**Additional context**

**Comment by iiTzRichie** [comment]
Hey,

Commenting because I was also experiencing this and I wanna let you know it now seems fixed as of Developer Beta 6/Public Beta 4.

**Comment by mvan231** [comment]
> Hey,
> 
> Commenting because I was also experiencing this and I wanna let you know it now seems fixed as of Developer Beta 6/Public Beta 4.

Agree! I see now it is fixed with the latest beta. Closing based on this
