### ISSUE TITLE
Red gifs not playing

### ISSUE THREAD

**Issue by AlexGadd** [christianselig/apollo-bugs#1795]
**Describe the bug**
No posts which use redgifs as a way to host gifs are currently working, simply shows an error saying “Redgifs error 😞 tap to open in browser”

**To Reproduce**
1. Look at any post which uses redgifs

**iOS version**: iOS 16 public Beta
**Apollo version**: 1.13.1
**iOS device**: iPhone 11
**Jailbroken**: No
**Reproducible:** yes
**Expected behavior**
To be able to posts which contain a gif which is a “redgif” 

**Screenshots**
![843056EC-F465-49BA-9BBB-D380643D3B1B](https://user-images.githubusercontent.com/8885350/187812027-93ee8636-6b3b-44dc-bd97-ba92faae8eb0.png)

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by Lobthon** [comment]
Same error here! No problems on reddits app. 
iPhone 12
iOS 15.6.1
Apollo 1.13.1

**Comment by jeremygc** [comment]
Same here 👍

Apollo 1.13.1
iOS 15.6.1

Opening a post with a Redgif image results in the following:

![image](https://user-images.githubusercontent.com/43440721/187833335-efebface-3465-4d12-a1a1-d0c4429fdd75.jpeg)

Clicking open in browser also does not show the image. Manually copying and pasting the image URL into a browser does show the image.

**Comment by Bbacon10** [comment]
Ya i've got the same thing.

**Comment by Knoneofyourbusiness** [comment]
Same here

**Comment by Dgrande13** [comment]
Same

**Comment by Mysundancer** [comment]
Same is happening to me as well!

**Comment by Twochains** [comment]
Same here iOS 15.6

**Comment by need2escape86** [comment]
Same issue here as well. Video just shows loading graphic, but if opened in browser, it loads immediately.

**Comment by k3vtr0n** [comment]
+1

on iPhone and iPad

**Comment by Mysundancer** [comment]
Why can’t someone fix this⁉️Aaaargh‼️

**Comment by armandhammer** [comment]
Same. Redgifs doesn’t load in Apollo anymore.

**Comment by Rumplown** [comment]
Same
iPhone 11 Pro
IOS 14.6
Apollo 1.13.1

**Comment by jh3r3d** [comment]
Yeah, same.
