### ISSUE TITLE
Subreddit weather not appearing in settings

### ISSUE THREAD

**Issue by Tabascus** [christianselig/apollo-bugs#1805]
The option is not appearing in Settings - Other. Currently on iOS 16 with latest Apollo (updated via App Store updates and even tried delete and reinstalling). 

Device is an iPhone 12 Pro Max. 

![DE30141A-ADA8-4CCD-A23B-2C5B8E46A304](https://user-images.githubusercontent.com/113387955/189747779-ea489160-692f-4876-96d5-f3a74c82b02a.png)

**Comment by zadigre** [comment]
Same problem here on my 13 pro max on iOS 16 and Apollo 1.14

![72D93B8D-B9A3-4D4C-ACB3-ECB1C6F0B5E4](https://user-images.githubusercontent.com/4810599/189779063-aefdb4a9-2012-425a-81d6-e8bac88e59dd.png)
![807C5B07-DA6E-4F21-97F6-AD5C27692DFC](https://user-images.githubusercontent.com/4810599/189779066-ad4334ae-e70e-465f-a989-d8adb79d878b.png)

**Comment by zadigre** [comment]
Ok… killed Apollo… and it’s there now

**Comment by zadigre** [comment]
today, the feature is gone again. definitely a bug.

**Comment by rlnunez** [comment]
On iOS 16.6 iPhone 11, same problem. On ver 1.14.8

![rAll](https://user-images.githubusercontent.com/10005996/198842348-836dc9e1-3919-48d8-bf57-cb8771849b5d.png)
