### ISSUE TITLE
'Posts' tab no longer returns you to Subreddits main page

### ISSUE THREAD

**Issue by FRABRACADABRA** [christianselig/apollo-bugs#1816]
**Describe the bug**
If you're in a comment thread, clicking the 'Posts' button on the bottom menu returns you to the subreddit.
Pressing the 'Posts' button again used to return to the Subreddits main page where it lists Home, Popular Posts, All Posts, Moderator Posts, etc. The button no longer does this

**To Reproduce**
1. View any subreddit (eg: r/All)
2. Click the 'Posts' button on the bottom menu
3. Don't get returned to the main Subreddits menu

**iOS version**: 16.0
**Apollo version**: 1.14.1
**iOS device**: 14 Pro
**Jailbroken**: No
**Reproducible:** Every time, including on app re-launch

**Screenshots**
![r all](https://user-images.githubusercontent.com/113735622/190831103-f776b96f-edfb-40c6-bfd1-915e111531f0.PNG)

Clicking the 'Posts' button used to return you to this screen:

![subreddit menu](https://user-images.githubusercontent.com/113735622/190831124-9ff3db31-bbf1-4ad7-932c-48d8f90e14b6.PNG)

**Comment by jensbodal** [comment]
Oddly you can get it to work again by clicking the search button and hitting cancel, then post button will take you back. It will stop working again though once you go into a subreddit 

iPhone 14 Pro Max

**Comment by FRABRACADABRA** [comment]
This appears to be fixed in 1.14.5
