### ISSUE TITLE
Home screen post widget appears to be broken since the last update

### ISSUE THREAD

**Issue by mrc0mmand** [christianselig/apollo-bugs#1817]
**Describe the bug**
Hey! After today's Apollo app update from 1.14 to 1.14.1 the home screen post widget stopped showing any data and is now completely empty (black, in my case). Neither re-adding the widget nor restarting the phone helped.

**To Reproduce**
Add a post widget to your home screen and observe.

**iOS version**: 16.0 (20A362)
**Apollo version**: 1.14.1
**iOS device**: iPhone XR
**Jailbroken**: no
**Reproducible:** reproducible every time with all of the home screen widgets (that show a feed of some subreddit)

**Expected behavior**
The home screen widget should show items from given subreddit/feed.

**Screenshots**
<details>
<summary>screenshots</summary>

![image](https://user-images.githubusercontent.com/679338/190854111-91e07938-d9e3-4732-b0c6-5733d951486b.png)
![image](https://user-images.githubusercontent.com/679338/190854113-65d536c1-db66-4c2e-a17e-ccd339d4fdbf.png)
![image](https://user-images.githubusercontent.com/679338/190854119-2635dcf7-68cb-40d7-bb7b-66f40614d902.png)
![image](https://user-images.githubusercontent.com/679338/190854158-f7c5fe00-ad42-47ae-aa49-f510bbb374fe.png)
</details>

**Additional context**
Also reported by users in https://www.reddit.com/r/apolloapp/comments/xgh9wz/apollo_home_screen_widget_doesnt_work/.

**Comment by rdenimal** [comment]
Hi there, I’m having the same issue on iPhone 13 Pro (iOS 16 20A362)

**Comment by tgpips** [comment]
I can confirm the issue is also happening on my iPad Pro 12.9” 5th gen running iPadOS 15.7 and Apollo 1.14.1. I tried a reinstall of Apollo just in case that fixed it but no joy.

**Comment by mrc0mmand** [comment]
Looks like this got resolved in just released 1.14.2, thanks, @christianselig, for a quick fix!
