### ISSUE TITLE
Return to previous position after returning to top no longer functioning

### ISSUE THREAD

**Issue by dnblankedelman** [christianselig/apollo-bugs#1831]
**Describe the bug**
I've always appreciated the feature that allows you to return to a previous scroll position should you have scrolled back to the top of a subreddit by mistake simply by tapping at the top again. It appears this feature has broken in either the latest release and/or connected to the new iPhone 14 Pro models. The second press (the one to return) seems to be ignored independent of where the pressing is done.

This is separately described in [this](https://www.reddit.com/r/apolloapp/comments/xgw86s/undo_feature_for_when_you_accidentally_tap_the/) and [this](https://www.reddit.com/r/apolloapp/comments/xjpro7/tapping_at_the_top_of_the_screen_a_second_time/) reddit post.

**To Reproduce**
1. Scroll down a reasonable amount in a subreddit.
2. Tap the top of the screen to return back to the top of the subreddit.
3. Tap the top of the screen in the fond hope of returning to your previous position.
4. Alas, no go backitude.

Specs: Apollo version 1.14.2 iOS version 16.0.1 iPhone 14 Pro, reproducible every time

**Expected behavior**
The glorious feature previously present would return you to the last position you were at when you scrolled back to the top.

Thanks!

**Comment by itsfatal** [comment]
Came here to report this same issue on my 14P.

**Comment by dnblankedelman** [comment]
Fixed in at least public release 1.14.5. Closing...
