### ISSUE TITLE
NavBar Disappearing in the Feed

### ISSUE THREAD

**Issue by th0jensen** [christianselig/apollo-bugs#1840]
**Describe the bug**
When scrolling in the feed, the navbar disappears consistently, and does not reappear until the View is reloaded.

**To Reproduce**
1. Go to the feed
2. Start scrolling, navbar disappears
3. Scroll up again, navbar doesn’t reappear
Workaround:
Leave the View by clicking a post. When you re-enter the view the navbar is back.

**iOS version**: iOS 16.1 (20B5050f)
**Apollo version**: 1.14.2
**iOS device**: iPhone 14 Pro Max
**Jailbroken**: N/A
**Reproducible:** Yes

**Expected behavior**
NavBar reappears when you stop scrolling or remains fixated at the bottom of the screen.

**Video**
Video on YouTube: https://youtube.com/shorts/6980Z_InW6w?feature=share

**Comment by dsemaya** [comment]
I’m seeing the nab bar disappear all over the app and it’s often hard to get it to show up again. I often have to force quit Apollo to see it again. It’s been pretty frustrating. iPhone 14 Pro.

**Comment by runnercto** [comment]
Super annoying!!!

**Comment by th0jensen** [comment]
This was fixed in the latest update. v1.14.5
