### ISSUE TITLE
[Usability] Live Text button blocks the bottom right corner of images

### ISSUE THREAD

**Issue by g-zhang** [christianselig/apollo-bugs#1868]
**Describe the bug**
The Live text button sits on the bottom right corner of images. This can block whatever is underneath it. Most of the time, this is not a an issue, but sometimes it can block text sitting at the bottom. My recommendation is to have the button sit below the image and have it draggable (for images that take up the whole screen) 

**To Reproduce**
1. Open an image post
2. Observe Live Text button covering the image bottom right corner. 

**iOS version**: 16.0.3
**Apollo version**: 1.14.5
**iOS device**: 13 pro
**Jailbroken**: No
**Reproducible:** Yes, 100%

**Expected behavior**
I want to be able to see the image unblocked by the button

**Screenshots**
See video

**Video**
https://streamable.com/ibego1
As you can see in the video, the image button is blocking that last character in the text. Dragging the image around doesn't work. Work around is to zoom in.

**Additional context**

**Comment by Kureb** [comment]
Hi, 

Christian already adressed this issue on [Reddit](https://reddit.com/r/apolloapp/comments/xeleiw/not_sure_if_its_ios_or_apollo_but_the_live_text/) . See below for his comment:

> Hmm, this is a tricky one. That’s indeed iOS UI that is placed there, I can’t shrink it exactly, but I can hide it (then you’d only be able to long-press on the text itself, and it might not be very discoverable).

> If you tap anywhere in the view it should hide it (along with the rest of the media viewer controls) so that’s something.


I’m using the tip to tap anywhere in the view to hide all the media viewer controls including the Live Text button and it works great.

Also you can inverse this behavior so all media viewer control are hidden by default and you would need to tap anywhere to display them:
`Settings > General > Show Controls When Opened (media section)`
