### ISSUE TITLE
MacOS - Apollo crashing when click on any post

### ISSUE THREAD

**Issue by rueshannbrantley** [christianselig/apollo-bugs#1894]
**Describe the bug**
On the Mac, Apollo is crashing when trying to open any post

**To Reproduce**
1. Launch Apollo
2. Click on any reddit post to view
3. App immediately crashes
4. 

**iOS version**: MacOS 13.0
**Apollo version**: 1.14.7 and 1.14.8
**iOS device**: M1 Max MacBook Pro 16"
**Jailbroken**: No
**Reproducible:** every time

**Video**

![CleanShot 2022-10-26 at 17 34 18](https://user-images.githubusercontent.com/32078013/198142984-4743d5f7-5ec1-4eeb-96a6-686782d54e15.gif)

**Comment by layandreas** [comment]
Same issue here on M1 Mac with MacOS 13.

**Comment by vandenbergrobin** [comment]
Same issue here on Version 1.14.7 (214)

**Comment by Avakining** [comment]
Still applies to 1.14.8

**Comment by nikorue** [comment]
same here, macOS 13.0 22A380 arm64, Apollo 1.14.8

**Comment by jaywelch** [comment]
+1
M2 MacBook Air
macOS Ventura 13.0
Opening URL links, images, gifs via thumbnail works, clicking on any reddit thread/comment link crashes app.

**Comment by evega2** [comment]
+1
M1 MacBook Pro
macOS Ventura 13.0


https://user-images.githubusercontent.com/19476257/199355837-08737e7c-746d-413a-ab41-5d458ebddb5c.mov

**Comment by forcedmeme** [comment]
+1 Macbook air m2.

**Comment by CrzHctr** [comment]
+1 on a 14 Macbook Pro M1 Pro

**Comment by maximilianblue** [comment]
+1 - 14 Macbook Pro M1 Pro MacOS 13.0

**Comment by gcanyon** [comment]
I had seen this on my M1 MacBook Air. Just updated to 1.14.9 and the problem has resolved.

**Comment by evega2** [comment]
Resolved in M1 Pro Macbook Pro macOS Venture 13.0

> +1 M1 MacBook Pro macOS Ventura 13.0
> 
>  apollo.mov

**Comment by rueshannbrantley** [comment]
The issue has been resolved for me since 1.14.9 has been released and others seem to agree. I am closing this bug report.
