### ISSUE TITLE
Loading MultiReddit stuck after switching account

### ISSUE THREAD

**Issue by neontorrent** [christianselig/apollo-bugs#1925]
**Describe the bug**
Loading MultiReddit stuck forever after switching to another account and back

**To Reproduce**
1. Go to a multireddit
2. Switch to another account
3. Switch back to the original account
4. Go to the same multireddit
5. It’s stuck with loading circle forever

**iOS version**: 16.1.1
**Apollo version**: 1.14.9
**iOS device**: iPhone 14 pro
**Jailbroken**: No
**Reproducible:** Always

**Expected behavior**
Multi reddit should load properly

**Screenshots**
![BCA025AC-B43A-4F0A-9B79-D4E04299DC21](https://user-images.githubusercontent.com/1185132/203006102-270f747b-d27f-4dfe-98e4-a19e4de2deb5.jpeg)

**Video**
NA

**Additional context**
NA

**Comment by neontorrent** [comment]
After clearing cache, multireddit will load properly, but after switching account it will have the same issue

**Comment by dezza** [comment]
Same issue for me, except I think it happens far more often and not only in cases of switching accounts. I'm clearing cache several times per day and almost every 2nd time I use it.
