### ISSUE TITLE
Home page (subscribed subreddits) doesn't load anything

### ISSUE THREAD

**Issue by bradley-rose** [christianselig/apollo-bugs#1946]
**Describe the bug**
Opening Apollo for Reddit defaults to the home page usually. This is the page that would load a compilation of top posts from an account's subscribed subreddits. This page is not loading any content. Navigating to an individual subreddit loads content just fine, but the home page will not load any content. 

**To Reproduce**
1. Open app, and/or navigate to Home

**iOS version**: 16.1.1
**Apollo version**: 1.14.16 
**iOS device**: iPhone 13 Mini
**Jailbroken**: No
**Reproducible:** Every time

**Expected behavior**
Content to be loaded from subscribed subreddits. Typical homepage behaviour. 

**Screenshots**
![image](https://user-images.githubusercontent.com/91505167/206310941-64a12cbf-cdc4-4a3c-bc52-e9c3b940df50.png)

**Comment by tox-lego** [comment]
I've been having the same problem for a few days, but only for my main account. 
My other account works just fine.
All other feeds are loading fine - it's just the Home feed using the "Best" sorting.

I've tried uninstalling the app and clearing the cache - no luck.
