### ISSUE TITLE
Apollo Ultra purchase screen missing header image on iPad

### ISSUE THREAD

**Issue by lotz** [christianselig/apollo-bugs#2060]
**Describe the bug**
The Apollo Ultra purchase screen is missing the header image on iPad, obscuring the "close" button (white button on white background). Additionally, the features list is only scrollable on the left side; it doesn't fill width.

**To Reproduce**
1. See screenshots.

**iOS version**: 16.4.1
**Apollo version**: 1.15.2
**iOS device**: iPad Pro
**Jailbroken**: No
**Reproducible:** Yes

**Expected behavior**
See screenshots.

**Screenshots**
iPad:
![image](https://user-images.githubusercontent.com/3892627/232316297-0fe610cb-8894-447c-8e06-c90ec6813224.jpeg)

iPhone:
![image](https://user-images.githubusercontent.com/3892627/232316304-7bc4ad37-2f3d-476a-b68a-b4806b3257cd.png)

**Comment by dkorunic** [comment]
Also when clicking on "All Plans", lifetime option seems to have disappeared.
