### ISSUE TITLE
app crashes when changing themes/app icon

### ISSUE THREAD

**Issue by pleasedonotdisturb** [christianselig/apollo-bugs#2089]
**Describe the bug**
Self-explanatory. The app instantly crashes whenever I change the app’s theme or the app icon. It’s a shame that customization becomes limited instantly after downloading the app.

**To Reproduce**
_For app theme_
1. Go to `Settings`
2. Click on `Appearance`
3. Click `Themes`
4. Pick any theme, doesn’t matter
5. App crashes

_For app icon_
1. Go to `Settings`
2. Click on `App Icon`
3. Pick any icon, doesn’t matter
4. App crashes

**iOS version**: 16.5
**Apollo version**: 1.15.9
**iOS device**: iPhone 12 Pro Max
**Jailbroken**: No
**Reproducible:** Yes

**Expected behavior**
I’m expecting the app theme would change, and so does the app icon when I exit the app.

**Screenshots**
N/A

**Video**
N/A

**Additional context**
N/A

**Comment by sauravsharma9149** [comment]
Yes. It does to mine too. But it is not just with themes. It is with enabling notifications, and changing the pixel buddy too. And many other settings.

**Comment by pleasedonotdisturb** [comment]
> Yes. It does to mine too. But it is not just with themes. It is with enabling notifications, and changing the pixel buddy too. And many other settings.

Good thing I’m not alone with this one. Speaking of Reddit, I hope that they would revert their API changes to original. I’m tired of the protests going on rn.
