### ISSUE TITLE
Apollo notification server

### ISSUE THREAD

**Issue by TechWizard402** [christianselig/apollo-bugs#225]
**Describe the bug**
The Apollo notification server hit my account activity about 10 times at 7am central and caused reddit to throw a suspicious activity flag on my account.

**iOS version**: ios13 beta 6
**Apollo version**: newest version
**phone type** iPhone XS Max 
**Jailbroken**: not jailbroken
**Reproducible:** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by christianselig** [comment]
Reddit catches false positives sometimes, I have no idea why
