### ISSUE TITLE
App doesn’t load reddit after password reset. 

### ISSUE THREAD

**Issue by CardenB** [christianselig/apollo-bugs#234]
**Describe the bug**
After resetting my password, the app fails to load anything from Reddit. 

**To Reproduce**
1. Go to reddit and reset password. 
2. Attempt to load home page or all. 
3. See only loading icon. 

**iOS version**: iOS 12
**Apollo version**: Version of Apollo this bug occurred on (can be found in Apollo's Settings tab > About)
**iOS device**: iPhone XS Max
**Jailbroken**: no
**Reproducible:** have not tried to reproduce. 
**Expected behavior**
I would have expected one of the tabs to load.

**Comment by ericswpark** [comment]
Same issue here. To workaround this problem, delete the account and re-add it. 

@christianselig maybe a check to see if the token is valid? It seems like the app isn't even checking if the token is valid before requesting data.

**Comment by haykam821** [comment]
This is fixed in Apollo 1.5:

!['Account Issue. Need to Re-Sign In.' popup](https://user-images.githubusercontent.com/24855774/64213322-8e492100-ce7a-11e9-8568-1b78101855b6.jpeg)

**Comment by christianselig** [comment]
Thanks all :)
