### ISSUE TITLE
Removed post appears for a second on open

### ISSUE THREAD

**Issue by tuminoid** [christianselig/apollo-bugs#239]
**Describe the bug**
Removed text isn't really removed, but appears for a second when opening a post, and can also be copied in full.

**To Reproduce**
1. Go to https://reddit.com/r/tifu/comments/cqftxv/tifu_by_going_to_the_emergency_room_after_pulling/ with Apollo
4. Post is seen for a second, then replaced by [removed]

**iOS version**: 12.4
**Apollo version**: 1.4.27
**iOS device**: iPhone XS Max
**Jailbroken**: No
**Reproducible:** For this post, and for me right now, it is

**Expected behavior**
Removed isn't seen.
Post text can also be copied via Share -> Text.

**Screenshots**
**Video**
https://youtu.be/4yxGnlTXqDk

**Additional context**
NSFW text in bug video.

**Comment by pfgithub** [comment]
This happens when a post was loaded already, like when browsing a subreddit. After you click on the post, it has to load it again to fetch comments and that's when it ipdates upvote counts and changes the post to [removed]

**Comment by tuminoid** [comment]
@pfgithub Maybe once, but you can observe this as many times as you want. It never caches that post is removed.

**Comment by tuminoid** [comment]
I think this has been fixed. Closing.
