### ISSUE TITLE
(1.5) Usernames can overlap with upvote button when displayed next to subreddit name

### ISSUE THREAD

**Issue by AveryVine** [christianselig/apollo-bugs#249]
**Describe the bug**
Long usernames can overlap with the upvote and downvote buttons when combined with long subreddit names.

**To Reproduce**
1. Enable usernames next to posts
2. Visit a subreddit with a long name (e.g. /r/humansbeingbros)
3. Find a post from a user with a long name
4. Observe overlapping name

**iOS version**: 13.0 developer beta 7
**Apollo version**: 1.5 beta
**iOS device**: iPhone X
**Jailbroken**: No
**Reproducible:** 100% reproducible

**Expected behavior**
Usernames should probably truncate right before colliding with the buttons.

**Screenshots**
![144AF918-4D1F-421B-9C1A-1E84E61830A9](https://user-images.githubusercontent.com/17837126/63223155-711f1c00-c205-11e9-8b89-f39c55a9c7aa.png)

**Video**
None

**Additional context**
Amazing work with the app! That’s all :)

**Comment by christianselig** [comment]
Thanks Avery!

**Comment by christianselig** [comment]
Fixed!
