### ISSUE TITLE
Icon switches back and forth o home screen 

### ISSUE THREAD

**Issue by nwhobart** [christianselig/apollo-bugs#289]
**Describe the bug**
When using Apollo swiping up on the screen to return to the home screen the previously used app icon briefly appears. After a beat or two the icon appears as expected

**To Reproduce**
1. Open Apollo
2. Enjoy reddit 
3. Swipe up on home screen 

**iOS version**: 13.0 (17A5572a)
**Apollo version**: 1.5
**iOS device**: iPhone XS
**Jailbroken**: No
**Reproducible:** Yes. Happens every time

**Expected Behavior**
Static icon

**Video**
Pending...

**Additional context**
Just bought lifetime Ultra. Unsure if related.

**Comment by nwhobart** [comment]
Duplicate of similar bug already posted.

**Comment by haykam821** [comment]
This is a duplicate of #279.
