### ISSUE TITLE
Apollo randomly logs me out on iPhone only

### ISSUE THREAD

**Issue by osianSmith** [christianselig/apollo-bugs#322]
**Describe the bug**
Apollo will randomly log me out of Reddit and keeps requiring me to log in. This only happens on my iPhone and does not occur on my iPad. 
**To Reproduce**
Cannot reproduce - occurs randomly

**iOS version**: 12.4.1 iPhone, 13.1 iPad
**Apollo version**:  1.5
**iOS device**: iPhone X and iPad Pro 11 inch 2017
**Jailbroken**: No 
**Reproducible:** No 

**Expected behavior**
To stay logged into Reddit
**Screenshots**
If possible, add screenshots to help show the problem.

**Additional context**

**Comment by SibCode** [comment]
This bug still exists as of today. Apollo randomly seems to log out of all previously linked accounts. This happened about three to five times in the last year. Once directly after an update and last again today.

iOS version: 13.5.1 iPhone
Apollo version: 1.8.4
iOS device: iPhone 7 plus
Jailbroken: No
Reproducible: No

**Comment by osianSmith** [comment]
Hi @SibCode 
This is no longer a problem for me and this ticket should have been closed a while back. Further the original ticket is in regards to a significantly older build of Appollo. This bug was fixed and your bug is likely to be unrelated to mine. 

I would suggest opening a new ticket for visibility.
