### ISSUE TITLE
Space bar on Smart Keyboard Folio doesn’t work in search field 

### ISSUE THREAD

**Issue by vgf1982** [christianselig/apollo-bugs#333]
**Describe the bug**
When inputing text in the search field, the space bar is not recognized when pressed, resulting in no space being executed. 

**To Reproduce**

1. Select the search field to input text
2. Input text using the Smart Keyboard Folio 
3. Attempt to use the space bar to input a space between search terms
4. The space is not recognized on the screen

**iOS version**: 12.4.1
**Apollo version**: 1.6
**iOS device**: 12.9” iPad Pro (2018 version)
**Jailbroken**: NOT jailbroken
**Reproducible:** Every time

**Expected behavior**
A space to be inserted between search terms

**Comment by cansas** [comment]
Same issue with Logitech Create keyboard - space bar not recognized for typing in any field.

iOS 13.1b4
Apollo 1.6
iPad Pro 9.7 (2017)

**Comment by RISCfuture** [comment]
Appears to be an issue with the Return key as well. Any word break key. (iPad 12.9” with Smart Folio)

**Comment by aeberbach** [comment]
Same with posting comments, Apollo 1.6, iPad Pro 12.9 + Apple Keyboard Folio, iOS 13.1 (17A5837a) not jailbroken. Spaces from the folio work fine in other apps.

**Comment by lutoma** [comment]
I think this applies to any input field in Apollo 1.6. Unfortunately this makes posting/commenting using an external keyboard nearly impossible.

Probably because `Space` and `Enter` are bound as shortcuts. For example if you type space in a subreddit search field, it will actually use the shortcut behaviour and scroll down the list of posts.

**Comment by ghost** [comment]
This isn't just a problem with search. It is universal. Cannot use space or enter with a smart keyboard.

**Comment by cansas** [comment]
App is essentially useless with external keyboards it seems.

**Comment by louisefindlay23** [comment]
Same for me with my Anne Pro 2 bluetooth keyboard.

**Comment by christianselig** [comment]
Fixed
