### ISSUE TITLE
Switching system-wide dark mode on or off crashes the app

### ISSUE THREAD

**Issue by Nykold** [christianselig/apollo-bugs#335]
Everytime I switch the system-wide dark mode on settings, the app crashes and immediately closes.

To reproduce simple:
1. Open the in-app settings
2. Go to themes
3. Switch system-wide dark mode on or off
4. The app crashes

Currently on iOS 13.1 Public Beta 4
Currently on Apollo 1.6
On the iPhone 8 Plus, not jailbroken

Reproducible everytime

Expected behaviour:
The app shouldn’t crash and exit to the iPhone’s main screen. It should instead remain open and simply start or stop using the system-wide dark mode setting.

**Comment by christianselig** [comment]
Fixed
