### ISSUE TITLE
IOS 12.4.1 on iPad — app doesn’t recognize space bar inputs

### ISSUE THREAD

**Issue by qweers** [christianselig/apollo-bugs#359]
**Describe the bug**
Since updating to the latest iPad software, I have not been able to get the app to recognize my keyboard’s space bar inputs.

**Comment by medgno** [comment]
I have this same issue on ipadOS 13.  It seems to work with the software keyboard but *not* with my hardware keyboard.

**Comment by zgmorris13** [comment]
Can confirm. I’m on a 2018 iPad Pro and having the same issue since updating to the latest iOS 12 version.

**Comment by zacklofgren** [comment]
I also have this issue in Apollo on iPadOS 13 on my iPad mini 5th gen.

**Comment by frankamedic** [comment]
Still an issue on iPadOS 13.1 on IPad Pro 11.

**Comment by mwdiers** [comment]
Just ran into this on the 12.9" iPad Pro Gen 3, on iPadOS 13.1. To be clear, this is only an issue on my hardware keyboard (folio keyboard cover). The software keyboard works fine.

**Comment by canyonblue737** [comment]
Same issue here, seems to have started when I updated to ios 13.1 on my ipad pro 11 inch. Apple smart keyboard space bar does not work in latest apollo only. Have attempted closing the app and reopening, rebooting the iPad etc. with no luck.

**Comment by mwdiers** [comment]
This is a bizarre bug for sure. It's only in Apollo, only on the hardware keyboard, only the spacebar, and only on the final 13.1 release.

For the record: Even on the last 13.1 beta prior to GM (developer beta 4), Apollo was working fine. Thanks, Apple.

**Comment by miguelarios** [comment]
I am also experiencing this too!

**Comment by mr100percent** [comment]
Experiencing this on both iOS 12.4.1 and iPadOS 13.1, both on Apollo 1.6. The bug occurs on Bluetooth keyboard, screen keyboard works without issue.

**Comment by christianselig** [comment]
Fixed
