### ISSUE TITLE
3D Touch no longer shows parent comment

### ISSUE THREAD

**Issue by raptormama** [christianselig/apollo-bugs#369]
It used to be possible to 3D Touch a comment to show the parent and press harder to get the parent to pop up over the window for easy reading. In 1.6.1 all this does is pop up the context menu. Please revert or provide an option toggle to enable this behavior.

I’m on an X with iOS 13.1 and long press set to maximum time required.

**Comment by drpebcak** [comment]
I second this. Same configuration - iPhone X, iOS 13.1, Apollo 1.6.1. I loved this feature!

**Comment by drpebcak** [comment]
Looks fixed in the latest update!

**Comment by raptormama** [comment]
Indeed it is!
