### ISSUE TITLE
(iOS 13.1) Smart Keyboard for iPad Pro 11 Space Key Not Working in Apollo 1.6

### ISSUE THREAD

**Issue by Drewood27** [christianselig/apollo-bugs#374]
**Describe the Bug**

Using the Smart Keyboard cover for iPad Pro 11, the space key has stopped working in text composition in Apollo 1.6. Pressing space on the home page causes the screen to scroll down with each press, but when attempting to type text, the space key does not respond. 

**To Reproduce**
1. Open a text composition window (new post, reply to post, etc.)
2. Begin typing. Space key does not create spaces in text.

**iOS version**: iOS 13.1 (iPad OS)
**Apollo version**: 1.6
**iOS device**: iPad Pro 11
**Jailbroken**: Not Jailbroken
**Reproducible:** Happens every time I try to compose text in Apollo 1.6.

**Expected behavior**
I expected pressing the space key to create a space in the text I was typing.

**Comment by christianselig** [comment]
Update Apollo to 1.6.1
