### ISSUE TITLE
Nav bar shifts up to top of the screen when sliding back to post list and and letting go

### ISSUE THREAD

**Issue by QuintB** [christianselig/apollo-bugs#398]
**Describe the bug**
Nav bar shifts up to top of the screen when sliding back to post list and and letting go

**To Reproduce**
1. Go to r/all
2. Tap on a post
3. Start dragging the post back from the left, as if you were returning to the main list view of r/all posts
4. Let go after dragging 1/8th of the way from the left edge, ie before the left side of the notch on X-series phones
5. See error

Also reproducible in settings tab.

**iOS version**: 13.2  Also happening on 13.1.x
**Apollo version**: 1.6.2
**iOS device**: iPhone 11 Pro
**Jailbroken**: Negatory Capt’n
**Reproducible:** Every time

**Expected behavior**
Nav bar is consistent throughout the entire interaction and does not jump up

**Screenshots**
![6C858743-EE3C-4FCE-BA53-E04BD0A06EE1](https://user-images.githubusercontent.com/50681031/66262775-49841300-e7b5-11e9-8b5d-05ec0e7d3ac5.png)

**Video**
https://streamable.com/zr8l4

**Comment by nk9** [comment]
No longer seeing this on 1.6.3. Is it fixed?

**Comment by QuintB** [comment]
Yes indeed. Thanks!

**Comment by nk9** [comment]
Great to hear! Be sure to close the bug then.
