### ISSUE TITLE
App freeze 

### ISSUE THREAD

**Issue by mentalBullet** [christianselig/apollo-bugs#409]
App freezes in regular interval. Sometimes while swiping back from a post, sometimes mid-scroll, and more.

**To Reproduce**
Can’t seem to reproduce it.

**iOS version**: 13.1.2
**Apollo Version**: 1.6.2
**iOS device**: iPhone 8 Plus
**Jailbroken**: No
**Reproducible:** No

**Expected behavior**
A smooth scrolling without freeze. 

**Screenshots**
If possible, add screenshots to help show the problem.

**Additional context**
App freezes about 4-5 seconds in a certain interval.

**Comment by tth80** [comment]
The issue is also present on iOS 13.1.3 (as it has on every version since 13.0.0), Apollo 1.6.2, iPhone 7 Plus.

I suspect it might be a network related since every time my connectivity drops or reception gets worse (like in an elevator) or I switch from wifi to LTE it will cause these freezes whenever it tries to make any kind of request (load more results, display comments, anything).

This did not happen on iOS 12.x so I can't say if it's something Apple changed or something Apollo changed.

**Comment by mentalBullet** [comment]
Yeah, my other phone with iOS 12 doesn’t have this issue.

Also, I started noticing after you made a comment but I don’t think that’s the reason. I’m on wifi all the time and it still happens. The wifi I’m connected to is consistent so I don’t think it’s the network.

**Comment by Alldred** [comment]
Same. I can’t seem to reproduce it. Happens once or twice a day, but as far as I’m aware I haven’t done anything obviously repeatable. 

(iOS 13.1.3, iPhone 11 Pro)

**Comment by tth80** [comment]
I think I may have figured it out. 
- Before iOS 13 I used the automatic theme change based on screen brightness. 
- When iOS 13 came out I switched to the "Use System Light/Dark Mode"
- Even if the theme doesn't change with the new setting, i think the app does something behind the scenes depending on the brightness, and freezes for the duration. I remember similar slowdown before when the theme changed automatically.
- Changing the theme setting back to "Switch Mode: Manually" resolves the issue for me, no more freezes or slowdowns. You have to disable "Use System Light/Dark Mode" before this.
- Re-enabling "Use System Light/Dark Mode" doesn't seem to affect it after making sure the switch mode is set to "Manually" before enabling it.

**Comment by Acen** [comment]
> I think I may have figured it out.
> 
> * Before iOS 13 I used the automatic theme change based on screen brightness.
> * When iOS 13 came out I switched to the "Use System Light/Dark Mode"
> * Even if the theme doesn't change with the new setting, i think the app does something behind the scenes depending on the brightness, and freezes for the duration. I remember similar slowdown before when the theme changed automatically.
> * Changing the theme setting back to "Switch Mode: Manually" resolves the issue for me, no more freezes or slowdowns. You have to disable "Use System Light/Dark Mode" before this.
> * Re-enabling "Use System Light/Dark Mode" doesn't seem to affect it after making sure the switch mode is set to "Manually" before enabling it.

This is indeed the fix for it, battling since the update. Thank you.

**Comment by Alldred** [comment]
> I think I may have figured it out.
> 
> * Before iOS 13 I used the automatic theme change based on screen brightness.
> * When iOS 13 came out I switched to the "Use System Light/Dark Mode"
> * Even if the theme doesn't change with the new setting, i think the app does something behind the scenes depending on the brightness, and freezes for the duration. I remember similar slowdown before when the theme changed automatically.
> * Changing the theme setting back to "Switch Mode: Manually" resolves the issue for me, no more freezes or slowdowns. You have to disable "Use System Light/Dark Mode" before this.
> * Re-enabling "Use System Light/Dark Mode" doesn't seem to affect it after making sure the switch mode is set to "Manually" before enabling it.

This works! Thank you!

**Comment by ghost** [comment]
> I think I may have figured it out.
> 
>     * Before iOS 13 I used the automatic theme change based on screen brightness.
> 
>     * When iOS 13 came out I switched to the "Use System Light/Dark Mode"
> 
>     * Even if the theme doesn't change with the new setting, i think the app does something behind the scenes depending on the brightness, and freezes for the duration. I remember similar slowdown before when the theme changed automatically.
> 
>     * Changing the theme setting back to "Switch Mode: Manually" resolves the issue for me, no more freezes or slowdowns. You have to disable "Use System Light/Dark Mode" before this.
> 
>     * Re-enabling "Use System Light/Dark Mode" doesn't seem to affect it after making sure the switch mode is set to "Manually" before enabling it.

I am going to try the same thing. I've been struggling with this for a while, each Apollo update has not fixed this. Very annoying, especially since you did all the work and found the solution.
