### ISSUE TITLE
“Filter from r/All” does not remove certain subreddits from the feed

### ISSUE THREAD

**Issue by wlincoln07** [christianselig/apollo-bugs#422]
**Describe the bug**
ShitPostCrusaders will not save to the Filtered subreddits list. I add it to the list every time it shows on the feed and it keeps showing back up. There are other subs that also won’t save. 

**To Reproduce**
1. Go to ‘ShitPostCrusaders’ subreddit
2. Click on '...’
3. Click on ‘Filter from r/All’
4. Subreddit does not save in ‘Filters and Blocks’
5. Subreddit continues to show in r/All

Also does not save when adding directly from Settings > Filter and Blocks

**iOS version**: 13.1.3
**Apollo version**: 1.6.2
**Device Model**: iPhone Xs 
**Jailbroken**: No
**Reproducible**: Yes

**Expected behavior**
When a subreddit is filtered from r/All it gets filtered from r/all permanently until it is manually removed from the filtered list. 

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by georgeperez** [comment]
Are you over 100 filtered subreddits? It won’t filter beyond those initial 100.

**Comment by wlincoln07** [comment]
Yep. That was it, thanks.
