### ISSUE TITLE
Can’t purchase Ultra pack

### ISSUE THREAD

**Issue by 0xab3d** [christianselig/apollo-bugs#424]
I can’t see the option to purchase Ultra pack on my iPhone XR
![84BEA6A7-B9CA-4DAE-AB2B-D11C75D33424](https://user-images.githubusercontent.com/4325064/67482535-efb88f80-f674-11e9-93af-fd7bd881d6f9.png)

**Comment by christianselig** [comment]
Could you include the template information on which version of iOS, etc. you're using please?

Also which country are you from?
