### ISSUE TITLE
Dark/Light Accidental Toggling - Bug or Feature?

### ISSUE THREAD

**Issue by butuzov** [christianselig/apollo-bugs#426]
**Describe the bug**
Theme changes on accident "taps" (white to dark, dark to white)

**To Reproduce**

1. Open Appolo
2. Click Search
3. Press Search field (Not Tap, But press)
4. Themes Toggles.

Used on two devices: iphone and ipad.
**iOS version**: 12.4, 12.1.13
**Apollo version**: 1.6.2, 1.4.27 and 1.6.2
**iOS device**: iPhoneX, iPad mini (2)
**Jailbroken**: Nope, Nope
**Reproducible:** YEs, its reproducible.

**Expected behavior**
Not switching themes but trying to copy something in search field or accidental taps

**Comment by LyricPants66133** [comment]
This is not a bug. There is actually a setting where you can toggle this on and off. Settings > Appearance > Enable/Disable quick switch
