### ISSUE TITLE
FaceID prompt is not triggered after Screen Time time limit extended

### ISSUE THREAD

**Issue by b-rare** [christianselig/apollo-bugs#45]
**Describe the bug**
After the iOS Screen Time App Limit is reached for Apollo, an iOS prompt appears to extend the time limit by 15 minutes or for the rest of the day. When FaceID is enabled in Apollo, selecting either App Limit prompt option yields the Apollo lock icon, but never triggers the FaceID interaction. 

**To Reproduce**
1. Configure an iOS Screen Time App Limit for Apollo (30 minutes in my case)
2. Enable FaceID for Apollo 
3. Keep Apollo open until time limit is reached
4. Select “Extend for 15 minutes” from the Screen Time prompt
5. Receive a lock screen with no FaceID prompt

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
12.2

**Apollo version**: Version of Apollo this bug occurred on (can be found in Apollo's Settings tab > About)
1.4.18

**iOS device**: For example iPhone XS, iPad mini, etc.
iPhone X

**Jailbroken**: Whether or not your device is jailbroken
No

**Reproducible:** Can you reproduce it every time? Or is it random?
Every time

**Expected behavior**
FaceID should be triggered after extending the App Limit time. 

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here.

**Additional context**

**Comment by b-rare** [comment]
Video: https://share.icloud.com/photos/0LdD69oIYY5lhPpHHuKOOkisw

**Comment by jehanalvani** [comment]
Been meaning to file a bug report on this. Glad to see it would have been a dupe.
