### ISSUE TITLE
"Default subreddit" is limited to 19 characters in length

### ISSUE THREAD

**Issue by Handcuffsofgold** [christianselig/apollo-bugs#478]
**Describe the bug**
When setting a default subreddit in Settings / General / Other / Default Reddit to Load, the "Set Subreddit" button becomes inactive as soon as 20 characters are typed into the subreddit name box. 19 characters is ok, 20 is not.

**To Reproduce**
1. Go to Settings / General / Other / Default Reddit to Load
2. Click on Subreddit
3. Type characters into the "Subreddit" box
4. See error as soon as 20th character is entered

**iOS version**: 13.2.2
**Apollo version**: 1.6.4
**iOS device**: Iphone XS
**Jailbroken**: No
**Reproducible:** Yes

**Expected behavior**
The "Subreddit" box should allow as many characters as are needed to enter the subreddit.

**Screenshots**
n/a

**Video**
Posted to /r/Apolloapp here with video of a screen recording: https://www.reddit.com/r/apolloapp/comments/dwjjgu/weird_bug_limit_to_19_characters_in_default/

**Additional context**
You are an awesome human and an amazing Canadian. Props to you Christian!

**Comment by christianselig** [comment]
Fixed in 1.7!
