### ISSUE TITLE
Video does not play in Apollo

### ISSUE THREAD

**Issue by AidanHak** [christianselig/apollo-bugs#54]
**Describe the bug**
Clicking on a certain video (and some other videos in the past) gives the a play sign with a cross through it in the middle of a black screen [like so](https://user-images.githubusercontent.com/24697869/57671012-dbf60100-75df-11e9-9bee-edb2a12659c7.png).

**To Reproduce**
1. Go to https://reddit.com/r/smashbros/comments/bobwk3/i_made_a_real_life_assist_trophy_that_holds/ in Apollo
2. Click on the video
3. Wait
4. It doesn't load.

**iOS version**: 12.2
**Apollo version**: 1.4.18
**iOS device**: iPhone 7
**Jailbroken**: Not jailbroken. 
**Reproducible:** For this specific Reddit post / YouTube video, it is reproducible.

**Expected behavior**
The video should at properly after clicking on it.

**Comment by AidanHak** [comment]
I restarted the app a few times last night and was able to reproduce. I can no longer reproduce this bug with the post I linked earlier. I'll add a comment later if I can reproduce it with another post.

**Comment by rosakala** [comment]
No I’m having the same issue too.  I have to long press the video and say open in safari.  When I do so instead of opening in safari it opens up in the app.
