### ISSUE TITLE
Filter from /All maxes-out at 99 subreddits

### ISSUE THREAD

**Issue by drcpbrown** [christianselig/apollo-bugs#545]
**Describe the bug**
Unable to add more than 99 subreddit filters.
Doesn’t work either adding from the settings/filters page, or from menu on each subreddit’s page.

**To Reproduce**
Attempt to filter further subreddits (I already have 99/100 or so filtered) - and they don’t get added to the list.

**iOS version**: 13.3
**Apollo version**: 16.6
**iOS device**: iPhone 11 Pro
**Jailbroken**: no
**Reproducible:** been happening for months!!

**Expected behavior**
unlimited subreddit filters, please!

**Screenshots**
(fairly self explanatory)

**Video**
(as above)

**Additional context**
N/a - just, thanks!!

**Comment by matthax** [comment]
This isn’t a bug it’s a reddit limitation. Additionally the 1.7 update will bring a new local filtering feature to solve this problem, so rest easy knowing it’ll be out soon.

**Comment by drcpbrown** [comment]
Many thanks for clarifying, looking forward to the update!
Best wishes, C
