### ISSUE TITLE
Inserting links with a text selection does not work correctly

### ISSUE THREAD

**Issue by matthax** [christianselig/apollo-bugs#546]
**Describe the bug**
Inserting a link after making a text selection does not replace the originally selected text.

**To Reproduce**
1. Go to a post or comment
2. Click to reply 
3. Type some text
4. Highlight the text you’ve typed
5. Hit the insert link button
6. Provide your link
7. Hit done, text is duplicated

**iOS version**: 13.3
**Apollo version**: 1.7
**iOS device**: iPhone X
**Jailbroken**: no
**Reproducible:** yessss

**Expected behavior**
Replace the highlighted text and insert the link.

**Video**

https://gfycat.com/craftyvigilantchimneyswift

**Additional context**
When testing I have already copied a link to my clipboard.

**Comment by nk9** [comment]
This duplicates #370.

**Comment by matthax** [comment]
Closing in favor of #370
