### ISSUE TITLE
WebViews are broken

### ISSUE THREAD

**Issue by MatrixSenpai** [christianselig/apollo-bugs#547]
**Describe the Bug**
All webviews appear to be broken everywhere

**To Reproduce**
1. Go to any link
2. Click on the link
3. Presented with a blank page

**iOS version**: 13.3
**Apollo version**: 1.7
**iOS device**: iPhone XS
**Jailbroken**: No
**Reproducible**: Always

**Screenshots**
![563A665A-6496-4489-9427-FF6FAD0404BC](https://user-images.githubusercontent.com/2157565/71536004-894c2980-28d0-11ea-80a0-51f58bd69c39.png)

**Video**
[A sample post](https://imgur.com/a/X62WDgd)

**Comment by mtwagner** [comment]
I am getting this too.

**Comment by MatrixSenpai** [comment]
This looks to be solved in the newer versions, closing
