### ISSUE TITLE
Unable to select text

### ISSUE THREAD

**Issue by NiklasBr** [christianselig/apollo-bugs#549]
**Describe the bug**

I wanted to select a word and get the dictionary definition using the “Look Up” iOS feature. But trying to long press a word (which works not other places) just opens a menu. 

**To Reproduce**
1. Go to any post
2. Long press a word in the post
3. See menu where small black pop up should be

**iOS version**: 13.3
**Apollo version**:  1.6.6 Pro
**iOS device**: iPhone SE
**Jailbroken**: No
**Reproducible:** All the time

**Expected behavior**
I expect to get something like this:

![C1ADC525-7989-4E36-BAF7-31D34BC66DE8](https://user-images.githubusercontent.com/279826/71556282-af8bd980-2a36-11ea-991a-796b75ac78ad.jpeg)

**Screenshots**
This menu appears instead:

![1C0C474F-DFFC-4C65-B04D-B14ADF1A56CE](https://user-images.githubusercontent.com/279826/71556283-ba466e80-2a36-11ea-8107-c91f6d01426d.png)

**Comment by joblolabinette** [comment]
If you scroll down in the menu that appear you should have select mode that appears then it will be possible to long press a word

**Comment by NiklasBr** [comment]
"Manie"?

**Comment by joblolabinette** [comment]
Sorry, just fixed my comment

**Comment by NiklasBr** [comment]
That just opens the post again for some reason

**Comment by joblolabinette** [comment]
![53D4FD1E-86A9-42D2-9072-B9C24DBE34CB](https://user-images.githubusercontent.com/3724319/72897551-3b201f80-3cf0-11ea-8ad0-d1088065f017.png)

**Comment by NiklasBr** [comment]
What actually is "Select mode" and why can't I select text in posts? Is it something I can enable?
