### ISSUE TITLE
Apollo showing wrong number of matches when searching comments 1.7

### ISSUE THREAD

**Issue by kubapilch** [christianselig/apollo-bugs#556]
**Describe the bug**
Number of matched words in comments is different from what Apollo shows in searchbar.

**To Reproduce**
1. Go to a thread
2. Search for some words that are used more than once
3. Count number of highlighted words by Apollo in comments and compare to the number that is displayed in searchbar

**iOS version**: 13.3.1
**Apollo version**: 1.7
**iOS device**: iPhone 6s
**Jailbroken**: No
**Reproducible:** Can reproduce.

**Expected behavior**
Displaying correct number of matches

**Video**

![RPReplay-Final1577978148](https://user-images.githubusercontent.com/21139232/71692625-be61eb80-2daa-11ea-949c-fa3ce7d4dfce.gif)

**Comment by christianselig** [comment]
Great report, thanks for the vid!
