### ISSUE TITLE
Shrug Text Face has too much escaping: ¯\\\_(ツ)\_/¯

### ISSUE THREAD

**Issue by zef** [christianselig/apollo-bugs#561]
**Describe the bug**
Shrug Text Face pastes as `¯\\\_(ツ)\_/¯` instead of `¯\_(ツ)_/¯`

Guessing there's too much character escaping?

**To Reproduce**
1. New Comment
2. Bring up "More Actions" menu
3. Select "Text Faces"
4. Select ¯\_(ツ)_/¯
5. See incorrect formatting

**iOS version**: 13.3
**Apollo version**: 1.6.6

![IMG_0746](https://user-images.githubusercontent.com/17274/72008374-e4efae80-3210-11ea-8fe7-9fccc9c3c242.jpg)

**Comment by krumble1** [comment]
I have 1.7.1 so my experience may differ, though your screenshot is identical to how it looks in this version.

The text that you show in the screenshot contains the correct amount of escaping necessary to display ¯\\\_(ツ)\_/¯ after the comment is posted. Try posting the comment, you'll see that it works correctly. Either that or something was changed in the most recent updates.

Either way, I believe this is resolved.

Tested on iOS 13.3, Apollo 1.7.1
