### ISSUE TITLE
Apollo Ultra lifetime subscription not active anymore

### ISSUE THREAD

**Issue by Rexios80** [christianselig/apollo-bugs#584]
**Describe the bug**
I purchased Apollo Ultra lifetime as soon as it was available. Today I opened the app and it said it couldn't find an active subscription.

**To Reproduce**
1. Open Apollo
2. I no longer have Apollo Ultra

**iOS version**: 13.3
**Apollo version**: 1.6.6
**iOS device**: iPhone 11 Pro Max
**Jailbroken**: No
**Reproducible:** Restarted app and phone. Still a problem.

**Expected behavior**
My subscription is still active.

**Comment by Rexios80** [comment]
I just looked at the subreddit and it seems to be an issue several people are having. It might be something we just have to wait out.

**Comment by xChryses** [comment]
Got the same issue here.
iPhone Xs
iOS 13.2

**Comment by GW619** [comment]
Same issue, began today. Restarting phone did not help. Deleting app & reinstalling did not fix either. 
iPhone 11 Pro Max, 13.3

**Comment by brettpetch** [comment]
If you guys try opening to resubscribe there should be a little button on the purchase screen that says “restore purchase”. This solved the problem to me.
