### ISSUE TITLE
App crashes on loading PIP video

### ISSUE THREAD

**Issue by Collectathon** [christianselig/apollo-bugs#585]
Steps to reproduce:
Find YouTube video in comments
Hold to activate picture-in-picture
Crashes

This happens with multiple videos. The video won’t load even when tapped on normally and crashes the app if tried to view in PIP mode.

Edit: Using latest version of Apollo Pro, iPhone 6S, iOS 13.3

**Comment by Xenophule** [comment]
Came here to report this. 
iPhone SE, iOS 13.3
