### ISSUE TITLE
Unable to select new “1s and 0s” app icon

### ISSUE THREAD

**Issue by PantsDragon** [christianselig/apollo-bugs#589]
**Describe the bug**
When trying to select the “1s and 0s” app icon from the new “Community Pack”, an error message is displayed and the app icon does not change. 

**To Reproduce**
1. Open Apollo
2. Tap Settings
3. Tap App icon
4. Tap Community Pack
5. Tap 1s and 0s
6. Observe error message

**iOS version**: 13.3.1
**Apollo version**: 1.7
**iOS device**: iPhone 11 Pro Max 
**Jailbroken**: No
**Reproducible:** Yes

**Expected behavior**
App icon should change and there should be a pop up message confirming success

**Screenshots**
Screenshot of error attached

![98E94806-D56C-4346-902F-679CAA93423F](https://user-images.githubusercontent.com/60447870/73393867-0a1c8d80-42a2-11ea-83ec-d75a072bd8a9.png)

**Video**
I recorded a video but can’t see how to attach via mobile interface, the photo attach button does not show videos in my photo library. 

**Additional context**
Every other new app icon seems to work both in community pack and then new Ultra icon. 

Force quit the app, issue remains.

**Comment by yar1vn** [comment]
Same. Came to report it.

**Comment by amolina157** [comment]
+1
![7AC00BEF-7170-414E-BA6C-CEE767A9C4C9](https://user-images.githubusercontent.com/8877506/73423322-ceadad80-42f9-11ea-9503-cecf5464b986.png)

**Comment by amolina157** [comment]
Fixed in the update 1.7.1 I think it was - thank you!

**Comment by PantsDragon** [comment]
Yup, this is fixed!
