### ISSUE TITLE
Notifications not showing up at all

### ISSUE THREAD

**Issue by Lochrine** [christianselig/apollo-bugs#671]
Hello.  Recently the app stopped showing notifications through my phone.  I posted on the subreddit, but didn’t get a response.  (Viewable under /u/SchalasHairDye)  Using an iPhone X and iOS 13.3.1.  App version 1.7.4.  Thanks!

**Comment by brandonkw123** [comment]
This has also occurred to me. iPhone 7+, same versions. I do have both Pro & Ultra.

**Comment by m0narch1** [comment]
I have the same issue. I paid for ultra but the notifications have never worked. iPhone 6s, iOS 13.3.1 and Apollo 1.7.4.

**Comment by arjunkomath** [comment]
Same experience for me, the only reason I bought Apollo Ultra was for getting push notification, but it doesn’t work.

Tried on iPad and iPhone.

**Comment by Lochrine** [comment]
It has actually been fixed for me for at least a month or so now, so I'm going to close the issue. If you are still experiencing this, I suggest you create a new issue with your specific specifications. Thanks!
