### ISSUE TITLE
"Mark Read on Scroll" not woring for some posts

### ISSUE THREAD

**Issue by alexandremjacques** [christianselig/apollo-bugs#689]
**Describe the bug**
After setting the "Mark Read on Scroll" on and scrolling on my "Home" listing, some posts are not marked as read after losing focus (leaving the screen). This also happens if I am inside a subreddit and not on "Home".

**To Reproduce**
1. Go to 'Settings → General → Mark Read / Hiding Posts → turn Mark Read on Scroll on'. Leave all other settings on this screen off.
2. Go back to Posts screen (further left bottom menu), select "Home"'
3. Scroll down to see some unread posts then scroll up to see that some posts are not marked as read.

**iOS version**: 13.4.1
**Apollo version**: 1.7.4
**iOS device**: iPhone Xr
**Jailbroken**: No
**Reproducible:** Can reproduce everytime

**Expected behavior**
I don't know if there's any post characteristic that should make a post not marked as read on listing but I would expect that all posts that are scrolled off screen should be marked as read (dimmed).

**Screenshots**
---

**Video**
Will update here as soon as I can reproduce the bug on video.

**Additional context**
It seems to be happening for a long time. Not only on this version.

**Comment by cookie-monster1649** [comment]
I have the same issue. Some posts just never mark as read when scrolling past them.
