### ISSUE TITLE
The starting screen logo has weird colors

### ISSUE THREAD

**Issue by frkd-dev** [christianselig/apollo-bugs#699]
**Describe the bug**
The dark theme starting screen logo has weird colors.

**To Reproduce**
1. Turn on a dark system theme.
2. Start the app.

**iOS version**: 13.4.1
**Apollo version**: 1.7.4
**iOS device**: iPhone X
**Jailbroken**: No
**Reproducible:** Always

**Expected behavior**
No weird colors in the logo.

**Screenshots**

![CA0D4618-F7B3-4978-AFA4-CE00D58FF0FC_1_105_c](https://user-images.githubusercontent.com/129271/81281759-88838b00-905a-11ea-873b-c238d6d8244d.jpeg)

**Video**
No

**Additional context**
No

**Comment by edeuss** [comment]
Yea noticed the same thing

**Comment by frkd-dev** [comment]
Fixed in recent versions
