### ISSUE TITLE
Some posts display in a serif font

### ISSUE THREAD

**Issue by haykam821** [christianselig/apollo-bugs#704]
Some posts and comments display in serif. In some views, they always will.

## Reproduction Steps

- Find a post or comment.
- It may use a serif font, instead of the correct sans-serif font.

## Versions

- **iOS version**: iOS 13.3
- **Apollo version**: 1.8 beta 1
- **iOS device**: For example iPhone XS, iPad mini, etc.
- **Jailbroken**: Yes
- **Reproducible:** Yes

## Expected Behavior

The posts display in Apollo's normal font.

## Screenshots

![Serif post](https://user-images.githubusercontent.com/24855774/81590119-563e9a00-9388-11ea-83a8-58212f8bdd97.jpg)

**Comment by lorinrivers** [comment]
I’m also seeing this. The post could be serif and some comments can also be serif, and others sans. I tried changing settings in Appearance but it doesn’t affect it.

**Comment by haykam821** [comment]
Fixed in beta 2
