### ISSUE TITLE
Apollo momentarily unresponsive upon reopening the app

### ISSUE THREAD

**Issue by andrewbraxton** [christianselig/apollo-bugs#723]
**Describe the bug**
When switching back to Apollo from another app, or opening Apollo from the home screen, the app is unresponsive for a few seconds.

**To Reproduce**
1. Open Apollo.
2. Switch apps or return to home screen.
3. Reopen Apollo. App remains unresponsive for several seconds.

**iOS version**: 13.4.1
**Apollo version**: 1.7.4
**iOS device**: iPhone XR
**Jailbroken**: No
**Reproducible:** Every time

**Expected behavior**
The app should be immediately responsive upon reopening the app.

**Video**
In this video I attempt to scroll as soon as Apollo reopens from the Settings app. It doesn’t respond for several seconds unlike when immediately attempting to scroll after switching to the Settings app.
https://streamable.com/o2ipb5

**Comment by AFRUITPIE** [comment]
iOS version: 13.5
Apollo version: 1.8 (build 52)
iOS device: iPhone X
Jailbroken: No

This issue has been popping up for me but reinstalling the app fixed it temporarily.

**Comment by andrewbraxton** [comment]
Appears fixed in new update. Will monitor for a few days before closing
