### ISSUE TITLE
Twitter links glitching out and freezing Twitter 

### ISSUE THREAD

**Issue by deadlynjdj** [christianselig/apollo-bugs#732]
**Describe the bug**
When opening linked in Twitter the official Twitter app will ask for a login. Once I put in the login it will say the Account was already been added and what  Attempting  to close out The app will stall

**To Reproduce**
1. Go to ' a post with a Twitter link’
2. Click on ' the preview of the link'

**13.5**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**1.7.4**: Version of Apollo this bug occurred on (can be found in Apollo's Settings tab > About)
**11 pro max **: For example iPhone XS, iPad mini, etc.
**non Jailbroken**: Whether or not your device is jailbroken
**Reproducible yes :** Can you reproduce it every time? Or is it random?

**Expected behavior**

**Screenshots**
If possible, add screenshots to help show the problem.

**Video**
If possible, attach a video to help show the problem. You can attach a video by uploading it to Streamable, Gfycat, YouTube, etc. and pasting the URL here. https://youtu.be/LVEy-HOap3I 

**Additional context**

**Comment by erniedeeb** [comment]
I can reproduce this issue reliably. Behavior recorded in OPs description and video Is identical to my own. 

iOS version: 13.4.1
Apollo version: 1.8, issue also occurred prior to the 1.8 update

**Comment by HiddenChin** [comment]
can confirm I am able to replicate this issue on my device.

iOS 13.5

Twitter works fine independently of Apollo, issue only occurs when trying to open links to twitter within Apollo

**Comment by RNorman1** [comment]
Just to clarify a bit - this seems to happen when you’re “timed out” of twitter.

The workaround is to:
1) force close Twitter
2) re-open twitter natively and allow it to load in (and log you in)
3) navigate back to Apollo and click the link
4) now that you have an “active session” (maybe not the correct terminology - but for lack of a better term), Apollo can redirect you to your link within twitter.

Must have something to do with not doing a call properly when it’s trying to launch twitter from Apollo if it’s not already open with an active session.

Issue seems to have started with the recent Apollo update (either 1.8 or 1.8.1).

iOS version: 13.4.1

Twitter version: 8.20
