### ISSUE TITLE
Most (YouTube) videos from /r/metalcore crash when viewed 

### ISSUE THREAD

**Issue by psydrin** [christianselig/apollo-bugs#737]
A large number of videos on the /r/metalcore subreddit crash when viewed in the new player. This happens to almost all of them on the 2018 iPad Pro 11-inch and about 1/3 of them on an iPhone XS Max. Many videos on other subreddits play just fine. It seems to be mostly music videos from what I can tell.

Very easy to reproduce. Just tap any video and once the preview starts loading and the video plays swipe down to dismiss it after a couple seconds and the app will crash.

**iOS version**: iOS 13.5
**Apollo version**: Version 1.8.1 
**iOS device**: iPhone XS Max and iPad Pro 11-inch (2018)
**Jailbroken**: No
**Reproducible:** Yes, reproducible every time for the videos that the app crashes on. This is most music videos on the iPad and slightly fewer on the iPhone. 

**Expected behavior**
The player should dismiss normally.

Edit: Updated to note this still occurs on 1.8.1. The videos still crash when swiping them closed but sometimes the same ones crash on their own now even without dismissing them.

**Comment by ddeville** [comment]
Also seeing this, not happening on all videos but this one is an example: https://reddit.com/r/Judaism/comments/gpfrb3/judaism_on_screen_an_old_one_but_still_the_most/

Closing the video either by swiping or tapping the close button crashes the app (my app should be sending the reports).

Not sure if it’s related but the videos where this happens I cannot scrub through. Also, when doing so the sound and image go out of sync.

**Comment by lanet95** [comment]
I also experienced this, specifically on YouTube videos.
