### ISSUE TITLE
Top comment missing when sorting comments

### ISSUE THREAD

**Issue by uchagani** [christianselig/apollo-bugs#80]
**Describe the bug**
If you sort comments (usually By Controversial), the top comment is missing. See screenshot below.

**To Reproduce**
1. Open comments on post
2. Sort by Controversial

**iOS version**: 12.2
**Apollo version**: 1.4.19
**iOS device**: iPhone XS Max
**Jailbroken**: No
**Reproducible:** Not always. If I force close Apollo and then re-open it it seems to work.

**Expected behavior**
Top comment should be visible

**Screenshots**

![](https://i.ibb.co/0yRNCm6/10113641-042-D-4741-84-B5-03-D704-C1-EB39.png)

**Comment by wheelchairpro** [comment]
Q&A sort also makes this happen.  The Auto-Moderator is not affected.

**Comment by sktgamerdudejr** [comment]
Sort by top makes it happen as well. Won’t happen if every sub, but happens about 50% (if not more) of the time. 

https://imgur.com/a/LHMoNv0
