### ISSUE TITLE
Tab bar and navigation bar do not reappear with Hide Bars on Scroll enabled

### ISSUE THREAD

**Issue by palle-k** [christianselig/apollo-bugs#832]
**Describe the bug**
When enabling the "Hide Bars on Scroll" setting, the navigation bar and tab bar often disappear permantently with the only fix being a restart of the app.

In some cases, the issue only affects the navigation bar, whereas the tab bar behaves normally.

**To Reproduce**
Not sure, seems to occur after Apollo has been open for a while. I do not have a step-by-step method to reproduce the issue.

**iOS version**: 13.5.5 (17G5035d) (issue has also been observed with previous official and beta iOS 13 releases)
**Apollo version**: 1.8.4 (Pro Enabled)
**iOS device**: iPhone XS Max
**Jailbroken**: No
**Reproducible:** Sometimes.

**Expected behavior**
The navigation bar and tab bar should appear when scrolling up after they disappeared when scrolling down

**Comment by thyman3** [comment]
Same issue here. I’m on a 2018 iPad Pro 12.9 with the most up to date iOS version. This happens often and only force-closing the app and reopening fixex the issue.
