### ISSUE TITLE
Upvoting a post or comment older than 6 months makes a popup

### ISSUE THREAD

**Issue by scratchyone** [christianselig/apollo-bugs#836]
**Describe the bug**
When you upvote an old post or comment it makes a popup show up telling you it’s too old. This makes it a pain to browse through old posts, like top of all time because you keep having to dismiss the popup when you try to upvote

**To Reproduce**
1. Find an old post or comment
2. Click upvote

**iOS version**: 13.3.1
**Apollo version**: 1.8.4
**iOS device**: iPhone XR
**Jailbroken**: Yes, but I don’t think it should matter here
**Reproducible:** Yes, always happens

**Expected behavior**
Like it used to, shouldn’t pop up so you don’t have to keep dismissing an annoying popup on old posts

**Screenshots**
![315A8BFD-4D38-406B-9BCF-C073DC8075F1](https://user-images.githubusercontent.com/11479077/84681454-22641080-af02-11ea-943f-f246d7c670c8.jpeg).

**Comment by LucasLarson** [comment]
> **Jailbroken**: Yes, but I don’t think it should matter here

I’m not Jailbroken. I am on Beta: iOS 13.6 (17G5045c). Here for the same reason.
