### ISSUE TITLE
Twitter preview not encoding/decoding "&" 

### ISSUE THREAD

**Issue by kkankala** [christianselig/apollo-bugs#89]
Twitter preview doesnt decode "&" character properly.

**To Reproduce**
1. Go to [Post](https://www.reddit.com/r/Cricket/comments/bt9al5/david_luiz_chelsea_footballer_message_for_virat/?utm_source=share&utm_medium=web2x)
2. Refer to &amp; in the preview.

**iOS version**: Version of iOS this bug occurred on (can be found in Settings.app > General)
**Apollo version**: Version of Apollo this bug occurred on (can be found in Apollo's Settings  public beta 2
**iOS device**: iPhone 8+
**Jailbroken**: No
**Reproducible:** Yes

**Expected behavior**
Show "&amp;" as &
**Screenshots**
If possible, add screenshots to help show the problem.
Expected screenshot:
![image](https://user-images.githubusercontent.com/14882633/58386556-881bec80-7fcf-11e9-88b9-fc4744b5b662.png)

**Comment by kkankala** [comment]
![3D6ECC03-9CCD-4E7F-95EC-0D0605ADC8C6](https://user-images.githubusercontent.com/14882633/58386568-b1d51380-7fcf-11e9-93b5-980651901bbb.png)
Screenshot of the error

**Comment by belak** [comment]
This still seems to be an issue. Using 1.6.5 on iOS 13.2.3 on an XS.

![FB9BEDFC-600F-4133-84F2-A0F15458B441](https://user-images.githubusercontent.com/107097/70254546-1967da80-173a-11ea-8ff2-40db9ed023ac.png)

Link to post: https://reddit.com/r/NintendoSwitch/comments/e699f8/6_classic_games_will_be_added_to_the_nes_snes/

**Comment by christianselig** [comment]
Fixed in 1.7, thanks :)
