### ISSUE TITLE
Overwriting default message for removal reason when removing post fails and posts original default reason.

### ISSUE THREAD

**Issue by Hydrochlorick** [christianselig/apollo-bugs#955]
**Describe the bug**
When deleting a post from the mod queue, one is prompted to add a removal reason, and picks from ones created for the sub. If one picks one of these reasons, chooses to post a public comment, but tries to overwrite the default text, it ignores the users input, and posts+stickies a comment with the default text. 

Additionally, the text field for editing said messages is WAYY too small. 

**To Reproduce**
1. Go to 'Mod Queue'
2. Remove any post
3. Choose to add removal reason
4. Pick any reason, choose to make a public reply
5. Overwrite default text to make a custom comment that is more specific to scenario
6. Double check post, and see your stickies comment with the default text. 

**iOS version**: iOS 14 Public Beta 4(whichever is the latest public beta as of 8/9/2020)
**Apollo version**: 1.8.6
**iOS device**: iPhone 11 Pro Max
**Jailbroken**: No
**Reproducible:** Occurs every time

**Expected behavior**
Post a public comment with the message that user just typed up in that tiny, inconvenient, single-line text box. 

**Video**
May create and add video later if developer cannot reproduce. 

**Additional context**
Did not thoroughly troubleshoot enough to see if this happens when deleting a post when simply navigating Reddit normally (as opposed to being done from mod queue), nor to see if it also happens when deleting comments.

**Comment by ghost** [comment]
I'm having this issue as well, so it makes it difficult to moderate using Apollo.

**Comment by christianselig** [comment]
Fixed in next build, thank you!
