### ISSUE TITLE
Video controls never show up on iOS/iPadOS14 beta 4

### ISSUE THREAD

**Issue by hzozo** [christianselig/apollo-bugs#956]
**Describe the bug**
The bug is that the media controls are not showing up for some videos in Apollo (no even after clicking/touching, no matter what I do, they never show), thus seeking/unmuting is very tricky/impossible. The bug I think started occurring after an update from beta 3 to this week's beta 4 but I'm not certain about that, it probably started occurring this week.

**To Reproduce**
1. Open this in Apollo on a device running iOS 14 beta 4 (iPhone or iPad, shouldn't matter): https://reddit.com/r/formula1/comments/i6posz/the_ongoing_hydration_banter_already_started/
2. Play video
3. The media controls shouldn't appear

**iOS version**: 14.0 (18A5342e)
**Apollo version**: 1.8.6
**iOS device**: iPhone 11 Pro, iPad Pro 11" (2018)
**Jailbroken**: No
**Reproducible:** Always reoccurring

**Expected behavior**
The media controls should show up as they do for all videos

**Video**
Screen recording link: https://share.icloud.com/photos/0_T12HfwRys6pNxU1gn2jcVsQ

**Comment by abulgatz** [comment]
Confirming the same issue after updating to iOS 14 beta 4. 

Additional beta 4 issue: videos are muted, even when they are set to be unmuted by default.

**Comment by SpudmanSpiff** [comment]
Same issues here, haven’t been able to hear or scrub videos at all now that I have beta 4

**Comment by jamesnelmore** [comment]
> Same issues here, haven’t been able to hear or scrub videos at all now that I have beta 4

You can't scrub? I have this issue too but I can scrub videos like gifs

**Comment by SpudmanSpiff** [comment]
> > Same issues here, haven’t been able to hear or scrub videos at all now that I have beta 4
> 
> You can't scrub? I have this issue too but I can scrub videos like gifs

Sorry I can scrub I meant that I can't play/pause or do anything pertaining to playback

**Comment by gentlemansbumtease** [comment]
Confirming this issue exists in iOS 14 Public Beta 5 as well

**Comment by jamesnelmore** [comment]
It appears to be fixed in the current build

**Comment by hzozo** [comment]
Can confirm the last statement, isn't a bug anymore on beta 6 of iOS 14.
