### ISSUE TITLE
Unable to download video from a crosspost or original post

### ISSUE THREAD

**Issue by silvetti** [christianselig/apollo-bugs#978]
**Describe the bug**
Unable to download video from a crosspost or original post.

Original post: 
https://www.reddit.com/r/WinStupidPrizes/comments/iie5vy/meanwhile_in_poland/
Crossposted to:
https://reddit.com/r/poland/comments/iiha33/meanwhile_in_poland/

**To Reproduce**
1. Go to post above in Apollo
2. Click video to play
3. Click ... and then select Download Video...

**iOS version**: 13.6.1
**Apollo version**: 1.8.6
**iOS device**: iPhone Xr
**Jailbroken**: No
**Reproducible:** On this video, every time.

**Expected behavior**
Ability to download said video from either crosspost or original post

**Screenshots**
![IMG_1297](https://user-images.githubusercontent.com/6786667/91629204-2b279700-e9c7-11ea-8535-6b3ba142026a.png)
<img width="790" alt="Screen Shot 2020-08-29 at 07 07 36" src="https://user-images.githubusercontent.com/6786667/91629182-0501f700-e9c7-11ea-9fd1-6523daf98699.png">

**Comment by Mshari117** [comment]
I came to report the same issue as I’m also getting the same error message.

**Comment by jotaro-gogogo** [comment]
Same happens for me on any video, but only videos not for gifs or pictures.
**iOS version:** 14 beta 7
**Apollo:** 1.8.6
**Device:** iPhone 8 Plus
**Jailbroken:** no
